export enum ContentArea {
  MAP = "Map",
  COMBAT = "Combat",
  SHOP = "Shop",
  INVENTORY = "Inventory",
  LABOUR = "Labour",
  MEDITATION = "Meditation",
  FISHING = "Fishing",
  MINING = "Mining",
  GATHERING = "Gathering",
  CULTIVATION_TREE = "Cultivation Tree",
  ALCHEMY = "Alchemy",
  FORGING = "Forging",
  IMMORTALS_ISLAND = "Immortals Island",
}
