import { CombatArea } from "../enum/CombatArea";
import type { CultivationPath } from "./cultivationPath";
import { totalXpForLevel } from "./fishingLevel";
import { totalXpForLevel as totalXpForMiningLevel } from "./miningLevel";
import { totalXpForLevel as totalXpForGatheringLevel } from "./gatheringLevel";
import EnemyI from "../interfaces/EnemyI";
import FishingAreaI from "../interfaces/FishingAreaI";
import GatheringAreaI from "../interfaces/GatheringAreaI";
import MiningAreaI from "../interfaces/MiningAreaI";
import Item from "../interfaces/ItemI";
import SectI from "../interfaces/SectI";
import SkillI from "../interfaces/SkillI";
import images from "./images";

/** Short descriptions for the Righteous vs Demonic path choice at game start. */
export const pathDescriptions: Record<CultivationPath, { title: string; description: string }> = {
  Righteous:
    { title: "Righteous Path", description: "Walk the path of virtue. Righteous sects and talents will open to you." },
  Demonic:
    { title: "Demonic Path", description: "Embrace the demonic way. Demonic sects and darker talents await." },
};

/** Sect positions/ranks. Order: 0 = Sect Aspirant (Mortal), 1 = Outer (Qi Condensation), 2 = Inner (Foundation), 3 = Core (Golden Core). */
/** requiredStepIndex: from realmProgression.getStepIndex (Mortal=0, QC1=1..10, FE1=11..20, Golden Core 1=21..30, …). */
export const SECT_POSITIONS = [
  { id: 0, name: "Sect Aspirant", requiredStepIndex: 0, requiredRealmLabel: "Mortal" },
  { id: 1, name: "Outer Disciple", requiredStepIndex: 1, requiredRealmLabel: "Qi Condensation" },
  { id: 2, name: "Inner Disciple", requiredStepIndex: 11, requiredRealmLabel: "Foundation Establishment" },
  { id: 3, name: "Core Disciple", requiredStepIndex: 21, requiredRealmLabel: "Golden Core" },
] as const;

export type SectPositionId = (typeof SECT_POSITIONS)[number]["id"];

/** One entry in a sect's store: item and minimum rank (0=Outer, 1=Inner, 2=Core) required to see/buy. */
export interface SectStoreEntryI {
  item: Item;
  requiredRankIndex: number;
}

/** Sect store by sect id. requiredRankIndex: 0=Sect Aspirant, 1=Outer, 2=Inner, 3=Core. */
export const sectStoreData: Record<number, SectStoreEntryI[]> = {
  1: [
    { item: { id: 600, name: "Jade Mountain Sword Manual", description: "Basic sword form. Unlocks sect combat technique.", price: 150, quantity: 1, picture: images.potion1, equipmentSlot: "qiTechnique", qiGainBonus: 0.15 }, requiredRankIndex: 1 },
    { item: { id: 601, name: "Mountain Heart Pill", description: "Sect pill for qi refinement.", price: 80, quantity: 1, picture: images.potion1, value: 5, effect: "attack" }, requiredRankIndex: 1 },
    { item: { id: 602, name: "Inner Gate Qi Circulation", description: "Inner disciple technique. +0.35 Qi/s when meditating.", price: 400, quantity: 1, picture: images.potion1, equipmentSlot: "qiTechnique", qiGainBonus: 0.35 }, requiredRankIndex: 2 },
    { item: { id: 603, name: "Jade Severance Recipe", description: "Alchemy recipe: Jade Severance Pill. Unlocks in Alchemy when learned.", price: 600, quantity: 1, picture: images.potion1 }, requiredRankIndex: 3 },
  ],
  2: [
    { item: { id: 610, name: "Valley Healing Herbs", description: "Herbs used in healing and pill recipes.", price: 60, quantity: 1, picture: images.potion1 }, requiredRankIndex: 1 },
    { item: { id: 611, name: "Verdant Qi Method", description: "Valley qi technique. +0.25 Qi/s when meditating.", price: 300, quantity: 1, picture: images.potion1, equipmentSlot: "qiTechnique", qiGainBonus: 0.25 }, requiredRankIndex: 1 },
    { item: { id: 612, name: "Valley Restoration Recipe", description: "Alchemy recipe: restoration pill. Requires Inner Disciple.", price: 500, quantity: 1, picture: images.potion1 }, requiredRankIndex: 2 },
    { item: { id: 613, name: "Elder's Meditation Scroll", description: "Core disciple only. +0.5 Qi/s when meditating.", price: 800, quantity: 1, picture: images.potion1, equipmentSlot: "qiTechnique", qiGainBonus: 0.5 }, requiredRankIndex: 3 },
  ],
  3: [
    { item: { id: 620, name: "Sky Pavilion Qi Primer", description: "Basic qi refinement manual.", price: 200, quantity: 1, picture: images.potion1, equipmentSlot: "qiTechnique", qiGainBonus: 0.2 }, requiredRankIndex: 1 },
    { item: { id: 621, name: "Azure Condensation Pill", description: "Pill that aids qi condensation.", price: 120, quantity: 1, picture: images.potion1, value: 8, effect: "attack" }, requiredRankIndex: 1 },
    { item: { id: 622, name: "High Peak Technique", description: "Inner disciple technique. +0.4 Qi/s when meditating.", price: 550, quantity: 1, picture: images.potion1, equipmentSlot: "qiTechnique", qiGainBonus: 0.4 }, requiredRankIndex: 2 },
    { item: { id: 623, name: "Pavilion Core Manual", description: "Core disciple combat and qi manual. Requires Core Disciple.", price: 1000, quantity: 1, picture: images.potion1 }, requiredRankIndex: 3 },
  ],
  4: [
    { item: { id: 630, name: "Crimson Demon Strike", description: "Basic demonic combat technique.", price: 180, quantity: 1, picture: images.potion1 }, requiredRankIndex: 1 },
    { item: { id: 631, name: "Blood Qi Pill", description: "Demonic qi pill.", price: 90, quantity: 1, picture: images.potion1, value: 6, effect: "attack" }, requiredRankIndex: 1 },
    { item: { id: 632, name: "Inner Demon Circulation", description: "Inner disciple. +0.35 Qi/s when meditating.", price: 450, quantity: 1, picture: images.potion1, equipmentSlot: "qiTechnique", qiGainBonus: 0.35 }, requiredRankIndex: 2 },
    { item: { id: 633, name: "Core Demon Art", description: "Forbidden technique. Core Disciple only.", price: 900, quantity: 1, picture: images.potion1, equipmentSlot: "qiTechnique", qiGainBonus: 0.55 }, requiredRankIndex: 3 },
  ],
  5: [
    { item: { id: 640, name: "Serpent Venom Recipe", description: "Basic poison recipe.", price: 100, quantity: 1, picture: images.potion1 }, requiredRankIndex: 1 },
    { item: { id: 641, name: "Shadow Step", description: "Assassin qi technique. +0.3 Qi/s when meditating.", price: 350, quantity: 1, picture: images.potion1, equipmentSlot: "qiTechnique", qiGainBonus: 0.3 }, requiredRankIndex: 1 },
    { item: { id: 642, name: "Inner Serpent Formula", description: "Poison formula. Requires Inner Disciple.", price: 480, quantity: 1, picture: images.potion1 }, requiredRankIndex: 2 },
    { item: { id: 643, name: "Shadow Serpent Core Manual", description: "Core disciple manual. Requires Core Disciple.", price: 850, quantity: 1, picture: images.potion1 }, requiredRankIndex: 3 },
  ],
  6: [
    { item: { id: 650, name: "Bone Refinement Pill", description: "Sect pill for bone tempering.", price: 110, quantity: 1, picture: images.potion1, value: 7, effect: "attack" }, requiredRankIndex: 1 },
    { item: { id: 651, name: "Abyss Qi Draw", description: "Basic abyss technique. +0.28 Qi/s when meditating.", price: 320, quantity: 1, picture: images.potion1, equipmentSlot: "qiTechnique", qiGainBonus: 0.28 }, requiredRankIndex: 1 },
    { item: { id: 652, name: "Undead Cultivation Fragment", description: "Inner disciple fragment. Requires Inner Disciple.", price: 520, quantity: 1, picture: images.potion1 }, requiredRankIndex: 2 },
    { item: { id: 653, name: "Bone Abyss Core Scripture", description: "Core disciple forbidden scripture. Requires Core Disciple.", price: 950, quantity: 1, picture: images.potion1, equipmentSlot: "qiTechnique", qiGainBonus: 0.52 }, requiredRankIndex: 3 },
  ],
};

/** Sects on the world map. 3 Righteous, 3 Demonic. positionX/Y are percentage (0–100) for map pin. */
export const sectsData: SectI[] = [
  { id: 1, name: "Jade Mountain Sect", description: "A righteous sect known for sword arts and strict discipline.", path: "Righteous", positionX: 23, positionY: 36 },
  { id: 2, name: "Verdant Valley Sect", description: "Righteous cultivators of the valley, masters of healing and herb lore.", path: "Righteous", positionX: 80, positionY: 75 },
  { id: 3, name: "Azure Sky Pavilion", description: "Righteous sect of the high peaks, focused on qi refinement and meditation.", path: "Righteous", positionX: 72, positionY: 16 },
  { id: 4, name: "Crimson Demon Sect", description: "Demonic sect that prizes strength and conquest above all.", path: "Demonic", positionX: 20, positionY: 65 },
  { id: 5, name: "Shadow Serpent Hall", description: "Demonic sect of assassins and poison masters.", path: "Demonic", positionX: 20, positionY: 85 },
  { id: 6, name: "Bone Abyss Sect", description: "Demonic sect that delves into forbidden arts and undead cultivation.", path: "Demonic", positionX: 77, positionY: 46},
];

export const existingShopItemUpgrades: Item[] = [
  {
    id: 1,
    name: "Wooden Spirit Blade",
    description: "A basic spirit weapon",
    price: 500,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png",
    quantity: 1,
  },
  {
    id: 2,
    name: "Iron Spirit Blade",
    description: "An iron spirit weapon",
    price: 1000,
    picture: "https://www.pokewiki.de/images/thumb/7/72/Sugimori_386.png/250px-Sugimori_386.png",
    quantity: 1,
  },
  {
    id: 3,
    name: "Gold Spirit Blade",
    description: "A gold spirit weapon",
    price: 10000,
    picture: "https://www.pokewiki.de/images/thumb/7/72/Sugimori_386.png/250px-Sugimori_386.png",
    quantity: 1,
  },
];

/** Black market items (e.g. Shadow Bazaar on map) – forbidden or rare wares. */
export const existingBlackMarketItems: Item[] = [
  {
    id: 500,
    name: "Forbidden Qi Pill",
    description: "Unrefined qi from questionable sources. Stronger, riskier.",
    price: 25,
    quantity: 1,
    picture: images.potion1,
    value: 3,
    effect: "attack",
  },
  {
    id: 501,
    name: "Blood Spirit Stone",
    description: "Spirit stone tinged with demonic essence. No questions asked.",
    price: 350,
    quantity: 1,
    picture: images.potion1,
    value: 25,
    effect: "attack",
  },
  {
    id: 502,
    name: "Veiled Meditation Scroll",
    description: "A technique not taught in righteous sects. +0.4 Qi/s when meditating.",
    price: 800,
    quantity: 1,
    picture: images.potion1,
    equipmentSlot: "qiTechnique",
    qiGainBonus: 0.4,
  },
];

export const existingShopItems: Item[] = [
  {
    id: 200,
    name: "Qi Pill",
    description: "Pill containing a bit of qi",
    price: 10,
    quantity: 1,
    picture: images.potion1,
    value: 1,
    effect: "attack",
  },
  {
    id: 201,
    name: "Foundation Pill",
    description: "Pill containing a bit of qi",
    price: 100,
    quantity: 1,
    picture: images.potion1,
    value: 10,
    effect: "attack",
  },
];

/** Qi technique equipment - can be bought and equipped in Qi Technique slot */
export const existingShopQiTechniques: Item[] = [
  {
    id: 400,
    name: "Basic Qi Circulation",
    description: "A simple technique. +0.2 Qi/s when meditating.",
    price: 200,
    quantity: 1,
    picture: images.potion1,
    equipmentSlot: "qiTechnique",
    qiGainBonus: 0.2,
  },
  {
    id: 401,
    name: "Spirit Gathering Method",
    description: "Improves qi absorption. +0.5 Qi/s when meditating.",
    price: 600,
    quantity: 1,
    picture: images.potion1,
    equipmentSlot: "qiTechnique",
    qiGainBonus: 0.5,
  },
];

export const existingSkills: SkillI[] = [
  { id: 3, name: "Meditation", description: "Cultivate Qi in solitude" },
  { id: 1, name: "Martial Training", description: "Train combat and face trials" },
  { id: 10, name: "Immortals Island", description: "Send expeditions for rewards" },
  { id: 2, name: "Labour", description: "Earn spirit stones" },
  { id: 4, name: "Fishing", description: "Fish in waters for spirit fish" },
  { id: 5, name: "Mining", description: "Mine ores and spirit stones" },
  { id: 6, name: "Gathering", description: "Gather herbs and wood" },
  { id: 8, name: "Alchemy", description: "Craft pills and elixirs" },
  { id: 9, name: "Forging", description: "Upgrade spirit weapons" },
  { id: 11, name: "Cooking", description: "Cook fish for food that restores vitality in combat" },
];

export const enemies: EnemyI[] = [
  {
    id: 1,
    name: "Young Spirit Beast",
    attack: 1,
    defense: 1,
    health: 10,
    location: CombatArea.FARM,
    picture: images.chicken,
    loot: { items: new Array(existingShopItems[0]), weight: [1] },
  },
  {
    id: 2,
    name: "Spirit Beast",
    attack: 3,
    defense: 3,
    health: 20,
    location: CombatArea.FARM,
    picture: images.cow,
    loot: { items: new Array(existingShopItems[0]), weight: [1] },
  },
  {
    id: 3,
    name: "Feral Spirit Beast",
    attack: 2,
    defense: 2,
    health: 15,
    location: CombatArea.FARM,
    picture: images.pig,
    loot: { items: new Array(existingShopItems[0]), weight: [1] },
  },
  {
    id: 4,
    name: "Cave Demon",
    attack: 5,
    defense: 5,
    health: 10,
    location: CombatArea.CAVE,
    picture: images.goblin,
    loot: { items: new Array(existingShopItems[0]), weight: [1] },
  },
];

/** Base path for fishing area images. Add images under public/assets/fishing/ */
const FISHING_ASSETS = "/assets/fishing";
/** Base path for fish item images. Add images under public/assets/fish/ */
const FISH_ASSETS = "/assets/fish";
/** Base path for mining area images. Add images under public/assets/mining/ */
const MINING_ASSETS = "/assets/mining";
/** Base path for mining loot item images (ore icons). */
const MINING_LOOT_ASSETS = "/assets/mining";
/** Base path for gathering area images. Add images under public/assets/gathering/ */
const GATHERING_ASSETS = "/assets/gathering";

/** Fishing areas: unlock by level (stored as XP via totalXpForLevel). Spread varied: ~5–10 levels between unlocks. */
export const fishingAreaData: FishingAreaI[] = [
  {
    id: 1,
    name: "Village Pond",
    fishingXP: 1,
    fishingXPUnlock: totalXpForLevel(1),
    fishingDelay: 3000,
    fishingLootIds: [301],
    picture: `${FISHING_ASSETS}/village-pond.png`,
    altText: "Village Pond – calm waters",
  },
  {
    id: 2,
    name: "Small Lake",
    fishingXP: 2,
    fishingXPUnlock: totalXpForLevel(8),
    fishingDelay: 3500,
    fishingLootIds: [301, 304],
    picture: `${FISHING_ASSETS}/small-lake.png`,
    altText: "Small Lake",
  },
  {
    id: 3,
    name: "Spirit River",
    fishingXP: 4,
    fishingXPUnlock: totalXpForLevel(16),
    fishingDelay: 4000,
    fishingLootIds: [301, 302, 304],
    picture: `${FISHING_ASSETS}/spirit-river.png`,
    altText: "Qi-rich flowing waters",
  },
  {
    id: 4,
    name: "Lotus Sect Lake",
    fishingXP: 7,
    fishingXPUnlock: totalXpForLevel(24),
    fishingDelay: 4500,
    fishingLootIds: [302, 306],
    picture: `${FISHING_ASSETS}/lotus-lake.png`,
    altText: "Lake filled with spirit lotuses",
  },
  {
    id: 5,
    name: "Spirit Sea",
    fishingXP: 11,
    fishingXPUnlock: totalXpForLevel(32),
    fishingDelay: 5000,
    fishingLootIds: [302, 303, 306],
    picture: `${FISHING_ASSETS}/spirit-sea.png`,
    altText: "Vast spiritual sea",
  },
  {
    id: 6,
    name: "Cloudfall Pools",
    fishingXP: 16,
    fishingXPUnlock: totalXpForLevel(41),
    fishingDelay: 5500,
    fishingLootIds: [306, 307, 308],
    picture: `${FISHING_ASSETS}/cloudfall-pools.png`,
    altText: "High mountain spirit pools",
  },
  {
    id: 7,
    name: "Frozen Moon Lake",
    fishingXP: 22,
    fishingXPUnlock: totalXpForLevel(50),
    fishingDelay: 6000,
    fishingLootIds: [309, 307],
    picture: `${FISHING_ASSETS}/frozen-lake.png`,
    altText: "Icy lake under eternal moonlight",
  },
  {
    id: 8,
    name: "Demon Abyss",
    fishingXP: 30,
    fishingXPUnlock: totalXpForLevel(59),
    fishingDelay: 6500,
    fishingLootIds: [305, 310],
    picture: `${FISHING_ASSETS}/demon-abyss.png`,
    altText: "Dark waters filled with demonic Qi",
  },
  {
    id: 9,
    name: "Heavenly River",
    fishingXP: 40,
    fishingXPUnlock: totalXpForLevel(68),
    fishingDelay: 7000,
    fishingLootIds: [311, 308],
    picture: `${FISHING_ASSETS}/heavenly-river.png`,
    altText: "River flowing through the heavens",
  },
  {
    id: 10,
    name: "Dragon Vein Ocean",
    fishingXP: 55,
    fishingXPUnlock: totalXpForLevel(76),
    fishingDelay: 7500,
    fishingLootIds: [312, 311],
    picture: `${FISHING_ASSETS}/dragon-ocean.png`,
    altText: "Ocean above a dragon vein",
  },
  {
    id: 11,
    name: "Blazing Crater Lake",
    fishingXP: 65,
    fishingXPUnlock: totalXpForLevel(83),
    fishingDelay: 7800,
    fishingLootIds: [313, 316],
    picture: `${FISHING_ASSETS}/crater-lake.png`,
    altText: "A volcanic lake radiating heat",
  },
  {
    id: 12,
    name: "Moonlit Reflection Pool",
    fishingXP: 70,
    fishingXPUnlock: totalXpForLevel(88),
    fishingDelay: 8000,
    fishingLootIds: [314, 319],
    picture: `${FISHING_ASSETS}/moon-pool.png`,
    altText: "Still waters reflecting the full moon",
  },
  {
    id: 13,
    name: "Falling Star Stream",
    fishingXP: 75,
    fishingXPUnlock: totalXpForLevel(92),
    fishingDelay: 8200,
    fishingLootIds: [315, 320],
    picture: `${FISHING_ASSETS}/star-stream.png`,
    altText: "A stream where stars are said to fall",
  },
  {
    id: 14,
    name: "Void Rift Waters",
    fishingXP: 82,
    fishingXPUnlock: totalXpForLevel(96),
    fishingDelay: 8500,
    fishingLootIds: [318, 321],
    picture: `${FISHING_ASSETS}/void-rift.png`,
    altText: "Waters bordering a spatial rift",
  },
  {
    id: 15,
    name: "Primordial Spirit Sea",
    fishingXP: 95,
    fishingXPUnlock: totalXpForLevel(99),
    fishingDelay: 9000,
    fishingLootIds: [322, 312, 320],
    picture: `${FISHING_ASSETS}/primordial-sea.png`,
    altText: "Ancient sea filled with primordial Qi",
  },
];

export const fishTypes: Item[] = [
  {
    id: 301,
    name: "Spirit Minnow",
    description: "A small fish touched by Qi. Can be used in pills. Restores 1 Qi.",
    price: 1,
    quantity: 1,
    picture: `${FISH_ASSETS}/spirit-minnow.png`,
    value: 1,
    effect: "qi",
  },
  {
    id: 302,
    name: "River Carp",
    description: "Common in Spirit River. Good for cooking.",
    price: 3,
    quantity: 1,
    picture: `${FISH_ASSETS}/river-carp.png`,
    value: 2,
    effect: "vitality",
  },
  {
    id: 303,
    name: "Jade Tuna",
    description: "Large spirit fish from the Spirit Sea.",
    price: 5,
    quantity: 1,
    picture: `${FISH_ASSETS}/jade-tuna.png`,
    value: 3,
    effect: "vitality",
  },
  {
    id: 304,
    name: "Silver Mackerel",
    description: "Swift fish rich in spiritual energy.",
    price: 2,
    quantity: 1,
    picture: `${FISH_ASSETS}/silver-mackerel.png`,
    value: 2,
    effect: "vitality",
  },
  {
    id: 305,
    name: "Abyssal Puffer",
    description: "Rare fish from the deep. Handle with care when preparing.",
    price: 7,
    quantity: 1,
    picture: `${FISH_ASSETS}/abyssal-puffer.png`,
    value: 5,
    effect: "vitality",
  },
  {
    id: 306,
    name: "Lotus Koi",
    description: "A koi raised among spirit lotuses. Calms the mind.",
    price: 6,
    quantity: 1,
    picture: `${FISH_ASSETS}/lotus-koi.png`,
    value: 4,
    effect: "qi",
  },
  {
    id: 307,
    name: "Azure Scale Eel",
    description: "An eel crackling with faint lightning Qi.",
    price: 8,
    quantity: 1,
    picture: `${FISH_ASSETS}/azure-eel.png`,
    value: 5,
    effect: "qi",
  },
  {
    id: 308,
    name: "Golden Spine Bass",
    description: "A rare bass with golden bones prized by alchemists.",
    price: 10,
    quantity: 1,
    picture: `${FISH_ASSETS}/golden-bass.png`,
    value: 6,
    effect: "vitality",
  },
  {
    id: 309,
    name: "Frostfin Trout",
    description: "Lives in icy waters. Body cold as jade.",
    price: 12,
    quantity: 1,
    picture: `${FISH_ASSETS}/frostfin-trout.png`,
    value: 7,
    effect: "vitality",
  },
  {
    id: 310,
    name: "Shadow Catfish",
    description: "Feeds in darkness. Favored by demonic cultivators.",
    price: 14,
    quantity: 1,
    picture: `${FISH_ASSETS}/shadow-catfish.png`,
    value: 8,
    effect: "qi",
  },
  {
    id: 311,
    name: "Celestial Salmon",
    description: "Swims against spiritual currents of heaven.",
    price: 18,
    quantity: 1,
    picture: `${FISH_ASSETS}/celestial-salmon.png`,
    value: 10,
    effect: "vitality",
  },
  {
    id: 312,
    name: "Dragon Vein Sturgeon",
    description: "Said to drink from dragon veins beneath the world.",
    price: 25,
    quantity: 1,
    picture: `${FISH_ASSETS}/dragon-sturgeon.png`,
    value: 14,
    effect: "qi",
  },
  {
    id: 313,
    name: "Emberfin Snapper",
    description: "A fish with warm, glowing scales. Said to live near magma springs.",
    price: 16,
    quantity: 1,
    picture: `${FISH_ASSETS}/emberfin-snapper.png`,
    value: 9,
    effect: "vitality",
  },
  {
    id: 314,
    name: "Moonwhisker Carp",
    description: "Active only under moonlight. Enhances spiritual awareness.",
    price: 18,
    quantity: 1,
    picture: `${FISH_ASSETS}/moonwhisker-carp.png`,
    value: 10,
    effect: "qi",
  },
  {
    id: 315,
    name: "Starfall Guppy",
    description: "Tiny fish that shimmer like falling stars.",
    price: 14,
    quantity: 1,
    picture: `${FISH_ASSETS}/starfall-guppy.png`,
    value: 8,
    effect: "qi",
  },
  {
    id: 316,
    name: "Thunderjaw Pike",
    description: "Its bite releases a crack of thunder.",
    price: 22,
    quantity: 1,
    picture: `${FISH_ASSETS}/thunderjaw-pike.png`,
    value: 12,
    effect: "vitality",
  },
  {
    id: 317,
    name: "Verdant Scale Tilapia",
    description: "Feeds on spirit herbs. Favored in alchemy.",
    price: 17,
    quantity: 1,
    picture: `${FISH_ASSETS}/verdant-tilapia.png`,
    value: 9,
    effect: "qi",
  },
  {
    id: 318,
    name: "Void Lantern Fish",
    description: "A deep-water fish that glows like a ghostly lantern.",
    price: 24,
    quantity: 1,
    picture: `${FISH_ASSETS}/void-lantern.png`,
    value: 13,
    effect: "qi",
  },
  {
    id: 319,
    name: "Crimson Banner Koi",
    description: "Symbol of fortune among sect elders.",
    price: 26,
    quantity: 1,
    picture: `${FISH_ASSETS}/crimson-koi.png`,
    value: 14,
    effect: "vitality",
  },
  {
    id: 320,
    name: "Heaven's Mirror Ray",
    description: "Its body reflects the sky like a mirror.",
    price: 28,
    quantity: 1,
    picture: `${FISH_ASSETS}/mirror-ray.png`,
    value: 15,
    effect: "qi",
  },
  {
    id: 321,
    name: "Nine-Whisker Catfish",
    description: "An ancient breed rumored to live for centuries.",
    price: 30,
    quantity: 1,
    picture: `${FISH_ASSETS}/ninewhisker-catfish.png`,
    value: 16,
    effect: "vitality",
  },
  {
    id: 322,
    name: "Mythic Pearl Eel",
    description: "Occasionally forms spirit pearls within its body.",
    price: 35,
    quantity: 1,
    picture: `${FISH_ASSETS}/pearl-eel.png`,
    value: 18,
    effect: "qi",
  },
];

/** Mining areas: unlock by level (stored as XP via totalXpForMiningLevel). */
export const miningAreaData: MiningAreaI[] = [
  {
    id: 1,
    name: "Copper Ore",
    miningXP: 1,
    miningXPUnlock: totalXpForMiningLevel(1),
    miningDelay: 4000,
    miningLootId: 501,
    picture: `${MINING_ASSETS}/copper-ore.png`,
    altText: "Copper ore vein",
  },
  {
    id: 2,
    name: "Iron Ore",
    miningXP: 2,
    miningXPUnlock: totalXpForMiningLevel(5),
    miningDelay: 5000,
    miningLootId: 502,
    picture: `${MINING_ASSETS}/iron-ore.png`,
    altText: "Iron ore vein",
  },
  {
    id: 3,
    name: "Spirit Vein",
    miningXP: 4,
    miningXPUnlock: totalXpForMiningLevel(10),
    miningDelay: 6000,
    miningLootId: 503,
    picture: `${MINING_ASSETS}/spirit-vein.png`,
    altText: "Spirit stone vein",
  },
  {
    id: 4,
    name: "Tin Seam",
    miningXP: 5,
    miningXPUnlock: totalXpForMiningLevel(15),
    miningDelay: 6200,
    miningLootId: 504,
    picture: `${MINING_ASSETS}/tin-seam.png`,
    altText: "Tin ore seam",
  },
  {
    id: 5,
    name: "Jade Deposit",
    miningXP: 7,
    miningXPUnlock: totalXpForMiningLevel(20),
    miningDelay: 6500,
    miningLootId: 505,
    picture: `${MINING_ASSETS}/jade-deposit.png`,
    altText: "Jade ore deposit",
  },
  {
    id: 6,
    name: "Silver Lode",
    miningXP: 9,
    miningXPUnlock: totalXpForMiningLevel(30),
    miningDelay: 7000,
    miningLootId: 506,
    picture: `${MINING_ASSETS}/silver-lode.png`,
    altText: "Silver ore lode",
  },
  {
    id: 7,
    name: "Gold Vein",
    miningXP: 12,
    miningXPUnlock: totalXpForMiningLevel(40),
    miningDelay: 7600,
    miningLootId: 507,
    picture: `${MINING_ASSETS}/gold-vein.png`,
    altText: "Gold ore vein",
  },
  {
    id: 8,
    name: "Obsidian Ridge",
    miningXP: 16,
    miningXPUnlock: totalXpForMiningLevel(50),
    miningDelay: 8200,
    miningLootId: 509,
    picture: `${MINING_ASSETS}/obsidian-ridge.png`,
    altText: "Obsidian outcrop",
  },
  {
    id: 9,
    name: "Thunder Crystal Cavern",
    miningXP: 18,
    miningXPUnlock: totalXpForMiningLevel(50),
    miningDelay: 8500,
    miningLootId: 508,
    picture: `${MINING_ASSETS}/thunder-cavern.png`,
    altText: "Cavern with lightning-charged crystals",
  },
  {
    id: 10,
    name: "Fallen Star Crater",
    miningXP: 24,
    miningXPUnlock: totalXpForMiningLevel(60),
    miningDelay: 9000,
    miningLootId: 510,
    picture: `${MINING_ASSETS}/star-crater.png`,
    altText: "Meteor crater rich with star iron",
  },
  {
    id: 11,
    name: "Voidstone Quarry",
    miningXP: 32,
    miningXPUnlock: totalXpForMiningLevel(70),
    miningDelay: 9800,
    miningLootId: 511,
    picture: `${MINING_ASSETS}/voidstone-quarry.png`,
    altText: "Quarry of light-bending voidstone",
  },
  {
    id: 12,
    name: "Dragonbone Strata",
    miningXP: 42,
    miningXPUnlock: totalXpForMiningLevel(80),
    miningDelay: 10500,
    miningLootId: 512,
    picture: `${MINING_ASSETS}/dragonbone-strata.png`,
    altText: "Ancient strata resembling dragon bones",
  },
  {
    id: 13,
    name: "Celestial Crystal Spire",
    miningXP: 58,
    miningXPUnlock: totalXpForMiningLevel(90),
    miningDelay: 11500,
    miningLootId: 513,
    picture: `${MINING_ASSETS}/celestial-spire.png`,
    altText: "Spire of radiant celestial crystals",
  },
  {
    id: 14,
    name: "Primordial Spirit Geode",
    miningXP: 70,
    miningXPUnlock: totalXpForMiningLevel(95),
    miningDelay: 12500,
    miningLootId: 513,
    picture: `${MINING_ASSETS}/primordial-geode.png`,
    altText: "A geode overflowing with condensed heavenly Qi",
  },
];

export const oreTypes: Item[] = [
  {
    id: 501,
    name: "Copper Ore",
    description: "Common copper ore. Used for basic tools and fittings.",
    price: 1,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/copper-ore.png`,
    value: 1,
    effect: "none",
  },
  {
    id: 502,
    name: "Iron Ore",
    description: "Reliable iron ore for weapons and armor.",
    price: 2,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/iron-ore.png`,
    value: 2,
    effect: "none",
  },
  {
    id: 503,
    name: "Spirit Stone",
    description: "A crystalline stone infused with Qi. Used in formations and cultivation.",
    price: 5,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/spirit-stone.png`,
    value: 4,
    effect: "qi",
  },
  {
    id: 504,
    name: "Tin Ore",
    description: "Soft metal ore used to alloy bronze and reinforce gear.",
    price: 2,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/tin-ore.png`,
    value: 2,
    effect: "none",
  },
  {
    id: 505,
    name: "Jade Ore",
    description: "Dense jade-like mineral prized for talismans and seals.",
    price: 6,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/jade-ore.png`,
    value: 5,
    effect: "qi",
  },
  {
    id: 506,
    name: "Silver Ore",
    description: "Conductive metal used in spirit circuits and charms.",
    price: 8,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/silver-ore.png`,
    value: 6,
    effect: "none",
  },
  {
    id: 507,
    name: "Gold Ore",
    description: "Rare noble metal used for high-grade crafting and tribute.",
    price: 10,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/gold-ore.png`,
    value: 7,
    effect: "none",
  },
  {
    id: 508,
    name: "Thunder Crystal",
    description: "A crackling crystal that stores lightning Qi.",
    price: 14,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/thunder-crystal.png`,
    value: 10,
    effect: "qi",
  },
  {
    id: 509,
    name: "Obsidian Shard",
    description: "Volcanic glass used for sharp blades and dark arrays.",
    price: 12,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/obsidian.png`,
    value: 9,
    effect: "none",
  },
  {
    id: 510,
    name: "Star Iron",
    description: "Meteor-forged iron that holds enchantments unusually well.",
    price: 18,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/star-iron.png`,
    value: 12,
    effect: "vitality",
  },
  {
    id: 511,
    name: "Voidstone",
    description: "A heavy stone that bends light. Used in spatial storage and rifts.",
    price: 22,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/voidstone.png`,
    value: 14,
    effect: "qi",
  },
  {
    id: 512,
    name: "Dragonbone Ore",
    description: "A bone-white mineral said to form near dragon veins.",
    price: 28,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/dragonbone-ore.png`,
    value: 18,
    effect: "vitality",
  },
  {
    id: 513,
    name: "Celestial Essence Crystal",
    description: "Radiant crystal condensed from heavenly Qi. Extremely valuable.",
    price: 40,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/celestial-crystal.png`,
    value: 25,
    effect: "qi",
  },
];

/** Gathering areas: unlock by level (stored as XP via totalXpForGatheringLevel). Spread varied for 1–99. */
export const gatheringAreaData: GatheringAreaI[] = [
  {
    id: 1,
    name: "Mortal Oak Grove",
    gatheringXP: 1,
    gatheringXPUnlock: totalXpForGatheringLevel(1),
    gatheringDelay: 4000,
    gatheringLootIds: [601],
    picture: `${GATHERING_ASSETS}/mortal-oak-grove.png`,
    altText: "Mortal Oak Grove",
  },
  {
    id: 2,
    name: "Hundred Herb Garden",
    gatheringXP: 1,
    gatheringXPUnlock: totalXpForGatheringLevel(1),
    gatheringDelay: 4000,
    gatheringLootIds: [611, 612],
    picture: `${GATHERING_ASSETS}/hundred-herb-garden.png`,
    altText: "Hundred Herb Garden",
  },
  {
    id: 3,
    name: "Iron Bamboo Forest",
    gatheringXP: 2,
    gatheringXPUnlock: totalXpForGatheringLevel(8),
    gatheringDelay: 4500,
    gatheringLootIds: [602],
    picture: `${GATHERING_ASSETS}/iron-bamboo-forest.png`,
    altText: "Iron Bamboo Forest",
  },
  {
    id: 4,
    name: "Spirit Grass Valley",
    gatheringXP: 4,
    gatheringXPUnlock: totalXpForGatheringLevel(16),
    gatheringDelay: 5000,
    gatheringLootIds: [613, 614],
    picture: `${GATHERING_ASSETS}/spirit-grass-valley.png`,
    altText: "Spirit Grass Valley",
  },
  {
    id: 5,
    name: "Ancient Cypress Peak",
    gatheringXP: 6,
    gatheringXPUnlock: totalXpForGatheringLevel(24),
    gatheringDelay: 5500,
    gatheringLootIds: [603],
    picture: `${GATHERING_ASSETS}/ancient-cypress-peak.png`,
    altText: "Ancient Cypress Peak",
  },
  {
    id: 6,
    name: "Heavenly Herb Cliff",
    gatheringXP: 8,
    gatheringXPUnlock: totalXpForGatheringLevel(32),
    gatheringDelay: 6000,
    gatheringLootIds: [614, 615, 616],
    picture: `${GATHERING_ASSETS}/heavenly-herb-cliff.png`,
    altText: "Heavenly Herb Cliff",
  },
  {
    id: 7,
    name: "Pine Hollow",
    gatheringXP: 10,
    gatheringXPUnlock: totalXpForGatheringLevel(41),
    gatheringDelay: 6500,
    gatheringLootIds: [604],
    picture: `${GATHERING_ASSETS}/pine-hollow.png`,
    altText: "Dense pine grove",
  },
  {
    id: 8,
    name: "Moonlit Herb Patch",
    gatheringXP: 12,
    gatheringXPUnlock: totalXpForGatheringLevel(50),
    gatheringDelay: 7000,
    gatheringLootIds: [616, 617],
    picture: `${GATHERING_ASSETS}/moonlit-herb-patch.png`,
    altText: "Herbs that bloom under moonlight",
  },
  {
    id: 9,
    name: "Ebony Grove",
    gatheringXP: 14,
    gatheringXPUnlock: totalXpForGatheringLevel(59),
    gatheringDelay: 7500,
    gatheringLootIds: [605],
    picture: `${GATHERING_ASSETS}/ebony-grove.png`,
    altText: "Dark ebony trees",
  },
  {
    id: 10,
    name: "Star Moss Vale",
    gatheringXP: 16,
    gatheringXPUnlock: totalXpForGatheringLevel(68),
    gatheringDelay: 8000,
    gatheringLootIds: [617, 618],
    picture: `${GATHERING_ASSETS}/star-moss-vale.png`,
    altText: "Valley of star-catching moss",
  },
  {
    id: 11,
    name: "Void Willow Stand",
    gatheringXP: 20,
    gatheringXPUnlock: totalXpForGatheringLevel(76),
    gatheringDelay: 8500,
    gatheringLootIds: [606],
    picture: `${GATHERING_ASSETS}/void-willow-stand.png`,
    altText: "Willows that drink from the void",
  },
  {
    id: 12,
    name: "Dragon Ash Thicket",
    gatheringXP: 24,
    gatheringXPUnlock: totalXpForGatheringLevel(83),
    gatheringDelay: 9000,
    gatheringLootIds: [607],
    picture: `${GATHERING_ASSETS}/dragon-ash-thicket.png`,
    altText: "Ashen wood from dragon lands",
  },
  {
    id: 13,
    name: "Primordial Herb Garden",
    gatheringXP: 28,
    gatheringXPUnlock: totalXpForGatheringLevel(88),
    gatheringDelay: 9500,
    gatheringLootIds: [618, 619, 620],
    picture: `${GATHERING_ASSETS}/primordial-herb-garden.png`,
    altText: "Ancient herbs from the dawn of Qi",
  },
  {
    id: 14,
    name: "Celestial Bamboo Grove",
    gatheringXP: 34,
    gatheringXPUnlock: totalXpForGatheringLevel(92),
    gatheringDelay: 10000,
    gatheringLootIds: [608],
    picture: `${GATHERING_ASSETS}/celestial-bamboo-grove.png`,
    altText: "Bamboo touched by heavenly Qi",
  },
  {
    id: 15,
    name: "Transcendent Spirit Peak",
    gatheringXP: 42,
    gatheringXPUnlock: totalXpForGatheringLevel(99),
    gatheringDelay: 11000,
    gatheringLootIds: [620, 621, 622],
    picture: `${GATHERING_ASSETS}/transcendent-spirit-peak.png`,
    altText: "Peak where spirit herbs reach beyond",
  },
];

export const woodTypes: Item[] = [
  {
    id: 601,
    name: "Oak Wood",
    description: "Common oak. Used for weapons and to light the alchemy forge.",
    price: 2,
    quantity: 1,
    picture: `${GATHERING_ASSETS}/item-oak-wood.png`,
    value: 0,
  },
  {
    id: 602,
    name: "Iron Bamboo",
    description: "Hard bamboo favoured by cultivators. Used in forging and cooking fires.",
    price: 5,
    quantity: 1,
    picture: `${GATHERING_ASSETS}/item-iron-bamboo.png`,
    value: 0,
  },
  {
    id: 603,
    name: "Spirit Cypress Wood",
    description: "Wood touched by Qi. Used for spirit weapons and high-grade alchemy.",
    price: 12,
    quantity: 1,
    picture: `${GATHERING_ASSETS}/item-spirit-cypress.png`,
    value: 0,
  },
  {
    id: 604,
    name: "Pine Wood",
    description: "Resinous pine. Burns long; used in alchemy and campfires.",
    price: 4,
    quantity: 1,
    picture: `${GATHERING_ASSETS}/item-pine-wood.png`,
    value: 0,
  },
  {
    id: 605,
    name: "Ebony Wood",
    description: "Dense dark wood. Used for high-grade crafting and arrays.",
    price: 14,
    quantity: 1,
    picture: `${GATHERING_ASSETS}/item-ebony-wood.png`,
    value: 0,
  },
  {
    id: 606,
    name: "Void Willow",
    description: "Willow that grows near rifts. Used in spatial and void arrays.",
    price: 20,
    quantity: 1,
    picture: `${GATHERING_ASSETS}/item-void-willow.png`,
    value: 0,
  },
  {
    id: 607,
    name: "Dragon Ash Wood",
    description: "Ashen wood from dragon territories. Used in top-tier forging.",
    price: 26,
    quantity: 1,
    picture: `${GATHERING_ASSETS}/item-dragon-ash-wood.png`,
    value: 0,
  },
  {
    id: 608,
    name: "Celestial Bamboo",
    description: "Bamboo infused with heavenly Qi. Used in transcendent alchemy.",
    price: 35,
    quantity: 1,
    picture: `${GATHERING_ASSETS}/item-celestial-bamboo.png`,
    value: 0,
  },
];

export const herbTypes: Item[] = [
  {
    id: 611,
    name: "Common Herb",
    description: "A basic herb. Used in pills and alchemy.",
    price: 1,
    quantity: 1,
    picture: `${GATHERING_ASSETS}/item-common-herb.png`,
    value: 0,
  },
  {
    id: 612,
    name: "Spirit Leaf",
    description: "Leaf imbued with faint Qi. Used in low-grade pills.",
    price: 2,
    quantity: 1,
    picture: `${GATHERING_ASSETS}/item-spirit-leaf.png`,
    value: 0,
  },
  {
    id: 613,
    name: "Spirit Grass",
    description: "Grass from spirit-rich soil. Used in alchemy pills.",
    price: 4,
    quantity: 1,
    picture: `${GATHERING_ASSETS}/item-spirit-grass.png`,
    value: 0,
  },
  {
    id: 614,
    name: "Silver Leaf",
    description: "Rare herb with a silvery sheen. Used in refinement pills.",
    price: 6,
    quantity: 1,
    picture: `${GATHERING_ASSETS}/item-silver-leaf.png`,
    value: 0,
  },
  {
    id: 615,
    name: "Jade Spirit Herb",
    description: "Precious herb favoured in high-level alchemy.",
    price: 10,
    quantity: 1,
    picture: `${GATHERING_ASSETS}/item-jade-spirit-herb.png`,
    value: 0,
  },
  {
    id: 616,
    name: "Heavenly Ginseng",
    description: "Rare ginseng said to touch the heavens. Used in breakthrough pills.",
    price: 15,
    quantity: 1,
    picture: `${GATHERING_ASSETS}/item-heavenly-ginseng.png`,
    value: 0,
  },
  {
    id: 617,
    name: "Moon Petal",
    description: "Herb that blooms under the full moon. Used in awareness pills.",
    price: 12,
    quantity: 1,
    picture: `${GATHERING_ASSETS}/item-moon-petal.png`,
    value: 0,
  },
  {
    id: 618,
    name: "Star Moss",
    description: "Moss that glows like starlight. Used in stellar alchemy.",
    price: 18,
    quantity: 1,
    picture: `${GATHERING_ASSETS}/item-star-moss.png`,
    value: 0,
  },
  {
    id: 619,
    name: "Primordial Root",
    description: "Root from the dawn of Qi. Used in ancient formulae.",
    price: 22,
    quantity: 1,
    picture: `${GATHERING_ASSETS}/item-primordial-root.png`,
    value: 0,
  },
  {
    id: 620,
    name: "Void Bloom",
    description: "Flower that grows near rifts. Used in void-attuned pills.",
    price: 28,
    quantity: 1,
    picture: `${GATHERING_ASSETS}/item-void-bloom.png`,
    value: 0,
  },
  {
    id: 621,
    name: "Celestial Lotus",
    description: "Lotus touched by heaven. Used in transcendent pills.",
    price: 34,
    quantity: 1,
    picture: `${GATHERING_ASSETS}/item-celestial-lotus.png`,
    value: 0,
  },
  {
    id: 622,
    name: "Transcendent Spirit Herb",
    description: "Herb that transcends mortal classification. Peak alchemy ingredient.",
    price: 45,
    quantity: 1,
    picture: `${GATHERING_ASSETS}/item-transcendent-herb.png`,
    value: 0,
  },
];

/** All gathering loot (wood + herbs) for lookup when completing a gather. */
export const gatheringLootTypes: Item[] = [...woodTypes, ...herbTypes];
