import { CombatArea } from "../enum/CombatArea";
import type { CultivationPath } from "./cultivationPath";
import { totalXpForLevel } from "./fishingLevel";
import { totalXpForLevel as totalXpForMiningLevel } from "./miningLevel";
import { totalXpForLevel as totalXpForGatheringLevel } from "./gatheringLevel";
import EnemyI from "../interfaces/EnemyI";
import FishingAreaI from "../interfaces/FishingAreaI";
import GatheringAreaI from "../interfaces/GatheringAreaI";
import MiningAreaI from "../interfaces/MiningAreaI";
import Item from "../interfaces/ItemI";
import SectI from "../interfaces/SectI";
import SkillI from "../interfaces/SkillI";
import { ALCHEMY_ASSETS } from "./alchemy";
import { COMBAT_LOOT_QI_PILLS } from "./alchemy";
import { RING_IDS, AMULET_IDS } from "./ringsAmulets";
import { TRAINING_ENEMIES } from "./training";

/** Base path for technique images (qi and combat). Place under public/assets/techniques/ */
const TECHNIQUES_ASSETS = "/assets/techniques";

/** Short descriptions for the Righteous vs Demonic path choice at game start. */
export const pathDescriptions: Record<CultivationPath, { title: string; description: string }> = {
  Righteous:
    { title: "Righteous Path", description: "Walk the path of virtue. Righteous sects and talents will open to you." },
  Demonic:
    { title: "Demonic Path", description: "Embrace the demonic way. Demonic sects and darker talents await." },
};

/** Sect positions/ranks. Order: 0 = Sect Aspirant (Mortal), 1 = Outer (Qi Condensation), 2 = Inner (Foundation), 3 = Core (Golden Core). */
/** requiredStepIndex: from realmProgression.getStepIndex (Mortal=0, QC1=1..10, FE1=11..20, Golden Core 1=21..30, …). */
export const SECT_POSITIONS = [
  { id: 0, name: "Sect Aspirant", requiredStepIndex: 0, requiredRealmLabel: "Mortal" },
  { id: 1, name: "Outer Disciple", requiredStepIndex: 1, requiredRealmLabel: "Qi Condensation" },
  { id: 2, name: "Inner Disciple", requiredStepIndex: 11, requiredRealmLabel: "Foundation Establishment" },
  { id: 3, name: "Core Disciple", requiredStepIndex: 21, requiredRealmLabel: "Golden Core" },
] as const;

export type SectPositionId = (typeof SECT_POSITIONS)[number]["id"];

/** One entry in a sect's store: item and minimum rank (0=Outer, 1=Inner, 2=Core) required to see/buy. */
export interface SectStoreEntryI {
  item: Item;
  requiredRankIndex: number;
}

/** All 15 qi techniques. #0 in basic shop; #1–14 from sects and monster drops. qiGainBonus is exponential: with base 1 Qi/s, totals go 2, 5, 10, 20, 50, 100, … */
export const QI_TECHNIQUES: Item[] = [
  { id: 700, name: "Gentle Breath Circulation", description: "A foundational technique. +2 Qi/s when meditating.", price: 200, quantity: 1, picture: `${TECHNIQUES_ASSETS}/breath-circulation.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 1 },
  { id: 701, name: "Flowing Meridian Method", description: "Qi flows along meridians. +5 Qi/s when meditating.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/flowing-meridian-method.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 4 },
  { id: 702, name: "Earth-Root Breathing Art", description: "Grounds the cultivator. +10 Qi/s when meditating.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/earth-root-breathing-art.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 9 },
  { id: 703, name: "Clear Mind Qi Cycle", description: "Clears the mind for refinement. +20 Qi/s when meditating.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/clear-mind-qi-cycle.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 19 },
  { id: 704, name: "Eight Meridian Resonance", description: "Resonates with the eight meridians. +50 Qi/s when meditating.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/eight-meridian-resonance.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 49 },
  { id: 705, name: "Jade Pulse Refinement", description: "Refines qi like jade. +100 Qi/s when meditating.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/jade-pulse-refinement.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 99 },
  { id: 706, name: "Spirit River Circulation", description: "Qi flows like a river. +200 Qi/s when meditating.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/spirit-river-circulation.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 199 },
  { id: 707, name: "Inner Sea Condensation Art", description: "Condenses qi in the inner sea. +500 Qi/s when meditating.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/inner-sea-condensation-art.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 499 },
  { id: 708, name: "Golden Core Resonance Method", description: "Resonates with the golden core. +2,000 Qi/s when meditating.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/golden-core-resonance-method.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 999 },
  { id: 709, name: "Heavenly Breath Harmonization", description: "Harmonizes with heavenly breath. +1,000 Qi/s when meditating.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/heavenly-breath-harmonization.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 1999 },
  { id: 710, name: "Starflow Meridian Scripture", description: "Qi follows the starflow. +5,000 Qi/s when meditating.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/starflow-meridian-scripture.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 4999 },
  { id: 711, name: "Void Pulse Refinement", description: "Refines the void pulse. +10,000 Qi/s when meditating.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/void-pulse-refinement.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 9999 },
  { id: 712, name: "Heaven-Earth Unity Technique", description: "Unifies heaven and earth. +20,000 Qi/s when meditating.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/heaven-earth-unity-technique.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 19999 },
  { id: 713, name: "Immortal Breath Sutra", description: "The breath of immortals. +50,000 Qi/s when meditating.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/immortal-breath-sutra.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 49999 },
  { id: 714, name: "Eternal Dao Circulation", description: "Circulation of the eternal Dao. +100,000 Qi/s when meditating.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/eternal-dao-circulation.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 99999 },
];

/** All 15 combat techniques. #0 in basic shop; #1–14 from sects and monster drops. Base attack interval 2 s; reduction is flat ms. */
export const COMBAT_TECHNIQUES: Item[] = [
  { id: 720, name: "Swift Wind Steps", description: "Basic footwork. Attack ×1.10, attack interval 1.95 s.", price: 250, quantity: 1, picture: `${TECHNIQUES_ASSETS}/swift-wind-steps.webp`, equipmentSlot: "combatTechnique", attackMultiplier: 1.1, attackSpeedReduction: 50 },
  { id: 721, name: "Flowing Blade Rhythm", description: "Blade moves in rhythm. Attack ×1.30, attack interval 1.93 s.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/flowing-blade-rhythm.webp`, equipmentSlot: "combatTechnique", attackMultiplier: 1.3, attackSpeedReduction: 70 },
  { id: 722, name: "Iron Body Assault Art", description: "Hardens the body for assault. Attack ×1.50, attack interval 1.91 s.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/iron-body-assault-art.webp`, equipmentSlot: "combatTechnique", attackMultiplier: 1.5, attackSpeedReduction: 90 },
  { id: 723, name: "Flashing Shadow Technique", description: "Strike from shadow. Attack ×1.70, attack interval 1.89 s.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/flashing-shadow-technique.webp`, equipmentSlot: "combatTechnique", attackMultiplier: 1.7, attackSpeedReduction: 110 },
  { id: 724, name: "Tiger Pounce Method", description: "Pounce like a tiger. Attack ×1.90, attack interval 1.87 s.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/tiger-pounce-method.webp`, equipmentSlot: "combatTechnique", attackMultiplier: 1.9, attackSpeedReduction: 130 },
  { id: 725, name: "Gale Strike Footwork", description: "Footwork like the gale. Attack ×2.10, attack interval 1.85 s.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/gale-strike-footwork.webp`, equipmentSlot: "combatTechnique", attackMultiplier: 2.1, attackSpeedReduction: 150 },
  { id: 726, name: "Thousand Fang Assault", description: "A thousand fangs. Attack ×2.30, attack interval 1.83 s.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/thousand-fang-assault.webp`, equipmentSlot: "combatTechnique", attackMultiplier: 2.3, attackSpeedReduction: 170 },
  { id: 727, name: "Stormblade Tempo", description: "The tempo of the storm blade. Attack ×2.50, attack interval 1.81 s.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/stormblade-tempo.webp`, equipmentSlot: "combatTechnique", attackMultiplier: 2.5, attackSpeedReduction: 190 },
  { id: 728, name: "Dragon Fang Momentum", description: "Momentum of the dragon fang. Attack ×2.70, attack interval 1.79 s.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/dragon-fang-momentum.webp`, equipmentSlot: "combatTechnique", attackMultiplier: 2.7, attackSpeedReduction: 210 },
  { id: 729, name: "Thunder Pulse Combat Art", description: "Combat like thunder. Attack ×2.90, attack interval 1.77 s.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/thunder-pulse-combat-art.webp`, equipmentSlot: "combatTechnique", attackMultiplier: 2.9, attackSpeedReduction: 230 },
  { id: 730, name: "Phantom Step Assault", description: "Assault with phantom steps. Attack ×3.10, attack interval 1.75 s.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/phantom-step-assault.webp`, equipmentSlot: "combatTechnique", attackMultiplier: 3.1, attackSpeedReduction: 250 },
  { id: 731, name: "Void Flash Technique", description: "Strike from the void. Attack ×3.30, attack interval 1.73 s.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/void-flash-technique.webp`, equipmentSlot: "combatTechnique", attackMultiplier: 3.3, attackSpeedReduction: 270 },
  { id: 732, name: "Heaven-Splitting Momentum", description: "Momentum that splits heaven. Attack ×3.50, attack interval 1.71 s.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/heaven-splitting-momentum.webp`, equipmentSlot: "combatTechnique", attackMultiplier: 3.5, attackSpeedReduction: 290 },
  { id: 733, name: "Celestial War Rhythm", description: "The rhythm of celestial war. Attack ×3.70, attack interval 1.69 s.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/celestial-war-rhythm.webp`, equipmentSlot: "combatTechnique", attackMultiplier: 3.7, attackSpeedReduction: 310 },
  { id: 734, name: "Immortal Slaughter Art", description: "The art of immortal slaughter. Attack ×3.90, attack interval 1.67 s.", price: 0, quantity: 1, picture: `${TECHNIQUES_ASSETS}/immortal-slaughter-art.webp`, equipmentSlot: "combatTechnique", attackMultiplier: 3.9, attackSpeedReduction: 330 },
];

/** Qi technique in basic shop (first of list). */
export const existingShopQiTechniques: Item[] = [QI_TECHNIQUES[0]];
/** Combat technique in basic shop (first of list). */
export const existingShopCombatTechniques: Item[] = [COMBAT_TECHNIQUES[0]];

/** Sect store by sect id. requiredRankIndex: 0=Sect Aspirant, 1=Outer, 2=Inner, 3=Core. */
export const sectStoreData: Record<number, SectStoreEntryI[]> = {
  1: [
    { item: { id: 600, name: "Jade Mountain Sword Manual", description: "Basic sword form. Unlocks sect combat technique.", price: 150, quantity: 1, picture: `${ALCHEMY_ASSETS}/potion1.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 0.15 }, requiredRankIndex: 1 },
    { item: { id: 601, name: "Mountain Heart Pill", description: "Sect pill for qi refinement.", price: 80, quantity: 1, picture: `${ALCHEMY_ASSETS}/potion1.webp`, value: 5, effect: "attack" }, requiredRankIndex: 1 },
    { item: { id: 602, name: "Inner Gate Qi Circulation", description: "Inner disciple technique. +0.35 Qi/s when meditating.", price: 400, quantity: 1, picture: `${ALCHEMY_ASSETS}/potion1.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 0.35 }, requiredRankIndex: 2 },
    { item: { id: 603, name: "Jade Severance Recipe", description: "Alchemy recipe: Jade Severance Pill. Unlocks in Alchemy when learned.", price: 600, quantity: 1, picture: `${ALCHEMY_ASSETS}/potion1.webp` }, requiredRankIndex: 3 },
    { item: QI_TECHNIQUES[1], requiredRankIndex: 1 },
    { item: QI_TECHNIQUES[2], requiredRankIndex: 2 },
    { item: COMBAT_TECHNIQUES[1], requiredRankIndex: 1 },
    { item: COMBAT_TECHNIQUES[2], requiredRankIndex: 2 },
  ],
  2: [
    { item: { id: 610, name: "Valley Healing Herbs", description: "Herbs used in healing and pill recipes.", price: 60, quantity: 1, picture: `${ALCHEMY_ASSETS}/potion1.webp` }, requiredRankIndex: 1 },
    { item: { id: 611, name: "Verdant Qi Method", description: "Valley qi technique. +0.25 Qi/s when meditating.", price: 300, quantity: 1, picture: `${ALCHEMY_ASSETS}/potion1.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 0.25 }, requiredRankIndex: 1 },
    { item: { id: 612, name: "Valley Restoration Recipe", description: "Alchemy recipe: restoration pill. Requires Inner Disciple.", price: 500, quantity: 1, picture: `${ALCHEMY_ASSETS}/potion1.webp` }, requiredRankIndex: 2 },
    { item: { id: 613, name: "Elder's Meditation Scroll", description: "Core disciple only. +0.5 Qi/s when meditating.", price: 800, quantity: 1, picture: `${ALCHEMY_ASSETS}/potion1.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 0.5 }, requiredRankIndex: 3 },
    { item: QI_TECHNIQUES[3], requiredRankIndex: 1 },
    { item: QI_TECHNIQUES[4], requiredRankIndex: 2 },
    { item: COMBAT_TECHNIQUES[3], requiredRankIndex: 1 },
    { item: COMBAT_TECHNIQUES[4], requiredRankIndex: 2 },
  ],
  3: [
    { item: { id: 620, name: "Sky Pavilion Qi Primer", description: "Basic qi refinement manual.", price: 200, quantity: 1, picture: `${ALCHEMY_ASSETS}/potion1.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 0.2 }, requiredRankIndex: 1 },
    { item: { id: 621, name: "Azure Condensation Pill", description: "Pill that aids qi condensation.", price: 120, quantity: 1, picture: `${ALCHEMY_ASSETS}/potion1.webp`, value: 8, effect: "attack" }, requiredRankIndex: 1 },
    { item: { id: 622, name: "High Peak Technique", description: "Inner disciple technique. +0.4 Qi/s when meditating.", price: 550, quantity: 1, picture: `${ALCHEMY_ASSETS}/potion1.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 0.4 }, requiredRankIndex: 2 },
    { item: { id: 623, name: "Pavilion Core Manual", description: "Core disciple combat and qi manual. Requires Core Disciple.", price: 1000, quantity: 1, picture: `${ALCHEMY_ASSETS}/potion1.webp` }, requiredRankIndex: 3 },
    { item: QI_TECHNIQUES[5], requiredRankIndex: 1 },
    { item: QI_TECHNIQUES[6], requiredRankIndex: 2 },
    { item: COMBAT_TECHNIQUES[5], requiredRankIndex: 1 },
    { item: COMBAT_TECHNIQUES[6], requiredRankIndex: 2 },
  ],
  4: [
    { item: { id: 630, name: "Crimson Demon Strike", description: "Basic demonic combat technique.", price: 180, quantity: 1, picture: `${ALCHEMY_ASSETS}/potion1.webp` }, requiredRankIndex: 1 },
    { item: { id: 631, name: "Blood Qi Pill", description: "Demonic qi pill.", price: 90, quantity: 1, picture: `${ALCHEMY_ASSETS}/potion1.webp`, value: 6, effect: "attack" }, requiredRankIndex: 1 },
    { item: { id: 632, name: "Inner Demon Circulation", description: "Inner disciple. +0.35 Qi/s when meditating.", price: 450, quantity: 1, picture: `${ALCHEMY_ASSETS}/potion1.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 0.35 }, requiredRankIndex: 2 },
    { item: { id: 633, name: "Core Demon Art", description: "Forbidden technique. Core Disciple only.", price: 900, quantity: 1, picture: `${ALCHEMY_ASSETS}/potion1.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 0.55 }, requiredRankIndex: 3 },
    { item: QI_TECHNIQUES[7], requiredRankIndex: 1 },
    { item: QI_TECHNIQUES[8], requiredRankIndex: 2 },
    { item: COMBAT_TECHNIQUES[7], requiredRankIndex: 1 },
    { item: COMBAT_TECHNIQUES[8], requiredRankIndex: 2 },
  ],
  5: [
    { item: { id: 640, name: "Serpent Venom Recipe", description: "Basic poison recipe.", price: 100, quantity: 1, picture: `${ALCHEMY_ASSETS}/potion1.webp` }, requiredRankIndex: 1 },
    { item: { id: 641, name: "Shadow Step", description: "Assassin qi technique. +0.3 Qi/s when meditating.", price: 350, quantity: 1, picture: `${ALCHEMY_ASSETS}/potion1.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 0.3 }, requiredRankIndex: 1 },
    { item: { id: 642, name: "Inner Serpent Formula", description: "Poison formula. Requires Inner Disciple.", price: 480, quantity: 1, picture: `${ALCHEMY_ASSETS}/potion1.webp` }, requiredRankIndex: 2 },
    { item: { id: 643, name: "Shadow Serpent Core Manual", description: "Core disciple manual. Requires Core Disciple.", price: 850, quantity: 1, picture: `${ALCHEMY_ASSETS}/potion1.webp` }, requiredRankIndex: 3 },
    { item: QI_TECHNIQUES[9], requiredRankIndex: 1 },
    { item: QI_TECHNIQUES[10], requiredRankIndex: 2 },
    { item: COMBAT_TECHNIQUES[9], requiredRankIndex: 1 },
    { item: COMBAT_TECHNIQUES[10], requiredRankIndex: 2 },
  ],
  6: [
    { item: { id: 650, name: "Bone Refinement Pill", description: "Sect pill for bone tempering.", price: 110, quantity: 1, picture: `${ALCHEMY_ASSETS}/potion1.webp`, value: 7, effect: "attack" }, requiredRankIndex: 1 },
    { item: { id: 651, name: "Abyss Qi Draw", description: "Basic abyss technique. +0.28 Qi/s when meditating.", price: 320, quantity: 1, picture: `${ALCHEMY_ASSETS}/potion1.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 0.28 }, requiredRankIndex: 1 },
    { item: { id: 652, name: "Undead Cultivation Fragment", description: "Inner disciple fragment. Requires Inner Disciple.", price: 520, quantity: 1, picture: `${ALCHEMY_ASSETS}/potion1.webp` }, requiredRankIndex: 2 },
    { item: { id: 653, name: "Bone Abyss Core Scripture", description: "Core disciple forbidden scripture. Requires Core Disciple.", price: 950, quantity: 1, picture: `${ALCHEMY_ASSETS}/potion1.webp`, equipmentSlot: "qiTechnique", qiGainBonus: 0.52 }, requiredRankIndex: 3 },
    { item: QI_TECHNIQUES[11], requiredRankIndex: 1 },
    { item: QI_TECHNIQUES[12], requiredRankIndex: 2 },
    { item: COMBAT_TECHNIQUES[11], requiredRankIndex: 1 },
    { item: COMBAT_TECHNIQUES[12], requiredRankIndex: 2 },
  ],
};

/** Sects on the world map. 3 Righteous, 3 Demonic. positionX/Y are percentage (0–100) for map pin. */
export const sectsData: SectI[] = [
  { id: 1, name: "Jade Mountain Sect", description: "A righteous sect known for sword arts and strict discipline.", path: "Righteous", positionX: 23, positionY: 36 },
  { id: 2, name: "Verdant Valley Sect", description: "Righteous cultivators of the valley, masters of healing and herb lore.", path: "Righteous", positionX: 80, positionY: 75 },
  { id: 3, name: "Azure Sky Pavilion", description: "Righteous sect of the high peaks, focused on qi refinement and meditation.", path: "Righteous", positionX: 72, positionY: 16 },
  { id: 4, name: "Crimson Demon Sect", description: "Demonic sect that prizes strength and conquest above all.", path: "Demonic", positionX: 20, positionY: 65 },
  { id: 5, name: "Shadow Serpent Hall", description: "Demonic sect of assassins and poison masters.", path: "Demonic", positionX: 20, positionY: 85 },
  { id: 6, name: "Bone Abyss Sect", description: "Demonic sect that delves into forbidden arts and undead cultivation.", path: "Demonic", positionX: 77, positionY: 46},
];

export const existingShopItemUpgrades: Item[] = [
  {
    id: 1,
    name: "Wooden Spirit Blade",
    description: "A basic spirit weapon",
    price: 500,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png",
    quantity: 1,
  },
  {
    id: 2,
    name: "Iron Spirit Blade",
    description: "An iron spirit weapon",
    price: 1000,
    picture: "https://www.pokewiki.de/images/thumb/7/72/Sugimori_386.png/250px-Sugimori_386.png",
    quantity: 1,
  },
  {
    id: 3,
    name: "Gold Spirit Blade",
    description: "A gold spirit weapon",
    price: 10000,
    picture: "https://www.pokewiki.de/images/thumb/7/72/Sugimori_386.png/250px-Sugimori_386.png",
    quantity: 1,
  },
];

/** Black market items (e.g. Shadow Bazaar on map) – forbidden or rare wares. */
export const existingBlackMarketItems: Item[] = [
  {
    id: 500,
    name: "Forbidden Qi Pill",
    description: "Unrefined qi from questionable sources. Stronger, riskier.",
    price: 25,
    quantity: 1,
    picture: `${ALCHEMY_ASSETS}/potion1.webp`,
    value: 3,
    effect: "attack",
  },
  {
    id: 501,
    name: "Blood Spirit Stone",
    description: "Spirit stone tinged with demonic essence. No questions asked.",
    price: 350,
    quantity: 1,
    picture: `${ALCHEMY_ASSETS}/potion1.webp`,
    value: 25,
    effect: "attack",
  },
  {
    id: 502,
    name: "Veiled Meditation Scroll",
    description: "A technique not taught in righteous sects. +0.4 Qi/s when meditating.",
    price: 800,
    quantity: 1,
    picture: `${ALCHEMY_ASSETS}/potion1.webp`,
    equipmentSlot: "qiTechnique",
    qiGainBonus: 0.4,
  },
];

export const existingShopItems: Item[] = [
  {
    id: 200,
    name: "Qi Pill",
    description: "Pill containing a bit of qi",
    price: 10,
    quantity: 1,
    picture: `${ALCHEMY_ASSETS}/potion1.webp`,
    value: 1,
    effect: "attack",
  },
  {
    id: 201,
    name: "Foundation Pill",
    description: "Pill containing a bit of qi",
    price: 100,
    quantity: 1,
    picture: `${ALCHEMY_ASSETS}/potion1.webp`,
    value: 10,
    effect: "attack",
  },
];

export const existingSkills: SkillI[] = [
  { id: 3, name: "Meditation", description: "Cultivate Qi in solitude" },
  { id: 1, name: "Martial Training", description: "Train combat and face trials" },
  { id: 10, name: "Immortals Island", description: "Send expeditions for rewards" },
  { id: 2, name: "Labour", description: "Earn spirit stones" },
  { id: 4, name: "Fishing", description: "Fish in waters for spirit fish" },
  { id: 5, name: "Mining", description: "Mine ores and spirit stones" },
  { id: 6, name: "Gathering", description: "Gather herbs and wood" },
  { id: 8, name: "Alchemy", description: "Craft pills and elixirs" },
  { id: 9, name: "Forging", description: "Upgrade spirit weapons" },
  { id: 11, name: "Cooking", description: "Cook fish for food that restores vitality in combat" },
];

/** Slug for enemy image filename: "Starving Wolf" -> "starving-wolf" (use .webp in public/assets/training/enemies/) */
function enemyImageSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "");
}

/** Combat area -> pill tier (0 = Basic Qi Pill, 9 = Transcendent). Used for scaled combat loot. */
const COMBAT_AREA_PILL_INDEX: Record<CombatArea, number> = {
  [CombatArea.FARM]: 0,
  [CombatArea.CAVE]: 1,
  [CombatArea.CRYSTALCAVE]: 2,
  [CombatArea.RIVER]: 3,
  [CombatArea.RUINS]: 4,
  [CombatArea.SWAMP]: 5,
  [CombatArea.RIFT]: 6,
  [CombatArea.PEAK]: 7,
  [CombatArea.SEA]: 8,
  [CombatArea.STORM]: 9,
  [CombatArea.PALACE]: 9,
};

export const enemies: EnemyI[] = [
  // Village Outskirts (Mortal)
  { id: 1, name: "Starving Wolf", attack: 1, defense: 1, health: 10, location: CombatArea.FARM, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Starving Wolf")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[0]], weight: [1] } },
  { id: 2, name: "Bandit Lookout", attack: 2, defense: 1, health: 12, location: CombatArea.FARM, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Bandit Lookout")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[0]], weight: [1] } },
  { id: 3, name: "Wild Boar", attack: 2, defense: 1, health: 14, location: CombatArea.FARM, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Wild Boar")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[0]], weight: [1] } },
  { id: 4, name: "Snake in the Grass", attack: 1, defense: 1, health: 8, location: CombatArea.FARM, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Snake in the Grass")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[0]], weight: [1] } },
  { id: 5, name: "Hungry Crow", attack: 1, defense: 0, health: 6, location: CombatArea.FARM, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Hungry Crow")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[0]], weight: [1] } },
  // Spirit Beast Cave (Qi Condensation)
  { id: 6, name: "Stonehide Bat", attack: 3, defense: 2, health: 18, location: CombatArea.CAVE, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Stonehide Bat")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[1]], weight: [1] } },
  { id: 7, name: "Ember-Eyed Weasel", attack: 4, defense: 2, health: 22, location: CombatArea.CAVE, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Ember-Eyed Weasel")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[1]], weight: [1] } },
  { id: 8, name: "Ripplefang Serpent", attack: 4, defense: 3, health: 25, location: CombatArea.CAVE, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Ripplefang Serpent")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[1]], weight: [1] } },
  { id: 9, name: "Cave Howler", attack: 5, defense: 3, health: 28, location: CombatArea.CAVE, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Cave Howler")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[1]], weight: [1] } },
  { id: 10, name: "Lesser Spirit Bear", attack: 5, defense: 4, health: 30, location: CombatArea.CAVE, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Lesser Spirit Bear")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[1]], weight: [1] } },
  // Crystal Mine (Foundation Establishment)
  { id: 11, name: "Shardback Lizard", attack: 6, defense: 4, health: 35, location: CombatArea.CRYSTALCAVE, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Shardback Lizard")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[2]], weight: [1] } },
  { id: 12, name: "Crystal Leech", attack: 5, defense: 5, health: 32, location: CombatArea.CRYSTALCAVE, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Crystal Leech")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[2]], weight: [1] } },
  { id: 13, name: "Quartz Golem", attack: 8, defense: 6, health: 45, location: CombatArea.CRYSTALCAVE, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Quartz Golem")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[2]], weight: [1] } },
  { id: 14, name: "Shardfang Spider", attack: 7, defense: 5, health: 38, location: CombatArea.CRYSTALCAVE, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Shardfang Spider")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[2]], weight: [1] } },
  { id: 15, name: "Mine Wraith", attack: 7, defense: 4, health: 40, location: CombatArea.CRYSTALCAVE, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Mine Wraith")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[2]], weight: [1] } },
  // Blackwater River Gorge (Golden Core)
  { id: 16, name: "Blackwater Crocodile", attack: 10, defense: 7, health: 55, location: CombatArea.RIVER, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Blackwater Crocodile")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[3]], weight: [1] } },
  { id: 17, name: "Bloodfin Carp Demon", attack: 9, defense: 6, health: 50, location: CombatArea.RIVER, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Bloodfin Carp Demon")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[3]], weight: [1] } },
  { id: 18, name: "Torrent Serpent", attack: 11, defense: 8, health: 60, location: CombatArea.RIVER, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Torrent Serpent")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[3]], weight: [1] } },
  { id: 19, name: "Mist-Reed Assassin", attack: 12, defense: 6, health: 52, location: CombatArea.RIVER, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Mist-Reed Assassin")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[3]], weight: [1] } },
  { id: 20, name: "Gorge Cliff Ape", attack: 11, defense: 9, health: 65, location: CombatArea.RIVER, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Gorge Cliff Ape")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[3]], weight: [1] } },
  // Ancient Sect Ruins (Nascent Soul)
  { id: 21, name: "Sect Remnant Puppet", attack: 14, defense: 10, health: 70, location: CombatArea.RUINS, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Sect Remnant Puppet")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[4]], weight: [1] } },
  { id: 22, name: "Seal-Script Specter", attack: 13, defense: 9, health: 68, location: CombatArea.RUINS, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Seal-Script Specter")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[4]], weight: [1] } },
  { id: 23, name: "Bronze Bell Revenant", attack: 15, defense: 11, health: 78, location: CombatArea.RUINS, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Bronze Bell Revenant")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[4]], weight: [1] } },
  { id: 24, name: "Dustbone Skeleton", attack: 14, defense: 10, health: 72, location: CombatArea.RUINS, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Dustbone Skeleton")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[4]], weight: [1] } },
  { id: 25, name: "Hallway Mirage", attack: 12, defense: 8, health: 65, location: CombatArea.RUINS, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Hallway Mirage")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[4]], weight: [1] } },
  // Thousand Miasma Marsh (Soul Formation)
  { id: 26, name: "Miasma Swamp Hag", attack: 18, defense: 13, health: 90, location: CombatArea.SWAMP, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Miasma Swamp Hag")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[5]], weight: [1] } },
  { id: 27, name: "Mudscale Basilisk", attack: 19, defense: 14, health: 95, location: CombatArea.SWAMP, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Mudscale Basilisk")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[5]], weight: [1] } },
  { id: 28, name: "Venom Lotus Sprite", attack: 17, defense: 12, health: 85, location: CombatArea.SWAMP, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Venom Lotus Sprite")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[5]], weight: [1] } },
  { id: 29, name: "Rotbloom Treant", attack: 20, defense: 15, health: 105, location: CombatArea.SWAMP, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Rotbloom Treant")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[5]], weight: [1] } },
  { id: 30, name: "Sporecloud Shambler", attack: 18, defense: 13, health: 92, location: CombatArea.SWAMP, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Sporecloud Shambler")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[5]], weight: [1] } },
  // Void Rift Expanse (Void Refinement)
  { id: 31, name: "Riftshade Stalker", attack: 24, defense: 18, health: 120, location: CombatArea.RIFT, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Riftshade Stalker")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[6]], weight: [1] } },
  { id: 32, name: "Void-Touched Scorpion", attack: 25, defense: 19, health: 125, location: CombatArea.RIFT, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Void-Touched Scorpion")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[6]], weight: [1] } },
  { id: 33, name: "Starless Horror", attack: 27, defense: 20, health: 135, location: CombatArea.RIFT, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Starless Horror")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[6], QI_TECHNIQUES[13]], weight: [8, 1] } },
  { id: 34, name: "Fraying Reality Wisp", attack: 23, defense: 17, health: 115, location: CombatArea.RIFT, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Fraying Reality Wisp")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[6]], weight: [1] } },
  { id: 35, name: "Astral Bonehound", attack: 26, defense: 19, health: 130, location: CombatArea.RIFT, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Astral Bonehound")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[6]], weight: [1] } },
  // Heavenpiercer Peak (Body Integration)
  { id: 36, name: "Stonevein Mountain Bear", attack: 30, defense: 23, health: 150, location: CombatArea.PEAK, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Stonevein Mountain Bear")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[7]], weight: [1] } },
  { id: 37, name: "Sky-Cutting Eagle", attack: 32, defense: 21, health: 145, location: CombatArea.PEAK, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Sky-Cutting Eagle")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[7]], weight: [1] } },
  { id: 38, name: "Frostwind Leopard", attack: 31, defense: 24, health: 155, location: CombatArea.PEAK, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Frostwind Leopard")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[7]], weight: [1] } },
  { id: 39, name: "Cloudstep Monkey", attack: 29, defense: 22, health: 142, location: CombatArea.PEAK, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Cloudstep Monkey")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[7]], weight: [1] } },
  { id: 40, name: "Sword-Sparring Hermit", attack: 34, defense: 26, health: 165, location: CombatArea.PEAK, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Sword-Sparring Hermit")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[7], COMBAT_TECHNIQUES[13]], weight: [8, 1] } },
  // Endless Cloudsea Sanctuary (Mahayana)
  { id: 41, name: "Cloudsea Serpent", attack: 38, defense: 29, health: 185, location: CombatArea.SEA, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Cloudsea Serpent")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[8]], weight: [1] } },
  { id: 42, name: "Lotus Guard Crane", attack: 37, defense: 30, health: 190, location: CombatArea.SEA, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Lotus Guard Crane")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[8]], weight: [1] } },
  { id: 43, name: "Rainbow Koi Monarch", attack: 39, defense: 28, health: 182, location: CombatArea.SEA, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Rainbow Koi Monarch")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[8]], weight: [1] } },
  { id: 44, name: "Celestial Herb Keeper", attack: 36, defense: 27, health: 178, location: CombatArea.SEA, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Celestial Herb Keeper")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[8]], weight: [1] } },
  { id: 45, name: "Cloud Palace Sentinel", attack: 40, defense: 32, health: 200, location: CombatArea.SEA, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Cloud Palace Sentinel")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[8]], weight: [1] } },
  // Nine Heavens Thunder Plateau (Tribulation Transcendent)
  { id: 46, name: "Thunderclap Roc", attack: 45, defense: 35, health: 225, location: CombatArea.STORM, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Thunderclap Roc")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[9]], weight: [1] } },
  { id: 47, name: "Lightning Wraith", attack: 44, defense: 34, health: 218, location: CombatArea.STORM, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Lightning Wraith")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[9]], weight: [1] } },
  { id: 48, name: "Stormforged Golem", attack: 47, defense: 37, health: 235, location: CombatArea.STORM, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Stormforged Golem")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[9]], weight: [1] } },
  { id: 49, name: "Tribulation Echo", attack: 46, defense: 36, health: 230, location: CombatArea.STORM, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Tribulation Echo")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[9]], weight: [1] } },
  { id: 50, name: "Crackling Sky Oni", attack: 48, defense: 38, health: 245, location: CombatArea.STORM, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Crackling Sky Oni")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[9], COMBAT_TECHNIQUES[14]], weight: [8, 1] } },
  // Jade Immortal Court (Immortal)
  { id: 51, name: "Jade Court Envoy", attack: 54, defense: 42, health: 270, location: CombatArea.PALACE, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Jade Court Envoy")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[9]], weight: [1] } },
  { id: 52, name: "Immortal Attendant", attack: 53, defense: 43, health: 275, location: CombatArea.PALACE, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Immortal Attendant")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[9]], weight: [1] } },
  { id: 53, name: "Golden Seal Arbiter", attack: 56, defense: 45, health: 285, location: CombatArea.PALACE, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Golden Seal Arbiter")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[9]], weight: [1] } },
  { id: 54, name: "Azure Hall Guardian", attack: 55, defense: 44, health: 280, location: CombatArea.PALACE, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Azure Hall Guardian")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[9]], weight: [1] } },
  { id: 55, name: "Celestial Punisher", attack: 58, defense: 47, health: 300, location: CombatArea.PALACE, picture: `${TRAINING_ENEMIES}/${enemyImageSlug("Celestial Punisher")}.webp`, loot: { items: [COMBAT_LOOT_QI_PILLS[9], QI_TECHNIQUES[14]], weight: [8, 1] } },
];

/** Base path for fishing area images. Add images under public/assets/fishing/ */
const FISHING_ASSETS = "/assets/fishing";
/** Base path for fish item images. Add images under public/assets/fish/ */
const FISH_ASSETS = "/assets/fish";
/** Base path for mining area images (location cards). Add under public/assets/mining/ */
const MINING_ASSETS = "/assets/mining";
/** Base path for mining loot item icons (ore in inventory). Add under public/assets/mining/items/ */
const MINING_LOOT_ASSETS = "/assets/mining/items";
/** Base path for gathering area images (location cards). Add under public/assets/gathering/ */
const GATHERING_ASSETS = "/assets/gathering";
/** Base path for gathering loot item icons (wood, herbs in inventory). Add under public/assets/gathering/items/ */
const GATHERING_ITEMS = "/assets/gathering/items";

/** Fishing areas: unlock by level (stored as XP via totalXpForLevel). Spread varied: ~5–10 levels between unlocks. */
export const fishingAreaData: FishingAreaI[] = [
  {
    id: 1,
    name: "Village Pond",
    fishingXP: 1,
    fishingXPUnlock: totalXpForLevel(1),
    fishingDelay: 3000,
    fishingLootIds: [301],
    picture: `${FISHING_ASSETS}/village-pond.webp`,
    altText: "Village Pond – calm waters",
  },
  {
    id: 2,
    name: "Small Lake",
    fishingXP: 2,
    fishingXPUnlock: totalXpForLevel(8),
    fishingDelay: 3500,
    fishingLootIds: [301, 304],
    picture: `${FISHING_ASSETS}/small-lake.webp`,
    altText: "Small Lake",
  },
  {
    id: 3,
    name: "Spirit River",
    fishingXP: 4,
    fishingXPUnlock: totalXpForLevel(16),
    fishingDelay: 4000,
    fishingLootIds: [301, 302, 304],
    picture: `${FISHING_ASSETS}/spirit-river.webp`,
    altText: "Qi-rich flowing waters",
  },
  {
    id: 4,
    name: "Lotus Sect Lake",
    fishingXP: 7,
    fishingXPUnlock: totalXpForLevel(24),
    fishingDelay: 4500,
    fishingLootIds: [302, 306],
    picture: `${FISHING_ASSETS}/lotus-lake.webp`,
    altText: "Lake filled with spirit lotuses",
  },
  {
    id: 5,
    name: "Spirit Sea",
    fishingXP: 11,
    fishingXPUnlock: totalXpForLevel(32),
    fishingDelay: 5000,
    fishingLootIds: [302, 303, 306],
    picture: `${FISHING_ASSETS}/spirit-sea.webp`,
    altText: "Vast spiritual sea",
  },
  {
    id: 6,
    name: "Cloudfall Pools",
    fishingXP: 16,
    fishingXPUnlock: totalXpForLevel(41),
    fishingDelay: 5500,
    fishingLootIds: [306, 307, 308],
    picture: `${FISHING_ASSETS}/cloudfall-pools.webp`,
    altText: "High mountain spirit pools",
  },
  {
    id: 7,
    name: "Frozen Moon Lake",
    fishingXP: 22,
    fishingXPUnlock: totalXpForLevel(50),
    fishingDelay: 6000,
    fishingLootIds: [309, 307],
    picture: `${FISHING_ASSETS}/frozen-lake.webp`,
    altText: "Icy lake under eternal moonlight",
  },
  {
    id: 8,
    name: "Demon Abyss",
    fishingXP: 30,
    fishingXPUnlock: totalXpForLevel(59),
    fishingDelay: 6500,
    fishingLootIds: [305, 310],
    picture: `${FISHING_ASSETS}/demon-abyss.webp`,
    altText: "Dark waters filled with demonic Qi",
  },
  {
    id: 9,
    name: "Heavenly River",
    fishingXP: 40,
    fishingXPUnlock: totalXpForLevel(68),
    fishingDelay: 7000,
    fishingLootIds: [311, 308],
    picture: `${FISHING_ASSETS}/heavenly-river.webp`,
    altText: "River flowing through the heavens",
    rareDropChancePercent: 1,
    rareDropItemIds: [AMULET_IDS.eightMeridian],
  },
  {
    id: 10,
    name: "Dragon Vein Ocean",
    fishingXP: 55,
    fishingXPUnlock: totalXpForLevel(76),
    fishingDelay: 7500,
    fishingLootIds: [312, 311],
    picture: `${FISHING_ASSETS}/dragon-ocean.webp`,
    altText: "Ocean above a dragon vein",
  },
  {
    id: 11,
    name: "Blazing Crater Lake",
    fishingXP: 65,
    fishingXPUnlock: totalXpForLevel(83),
    fishingDelay: 7800,
    fishingLootIds: [313, 316],
    picture: `${FISHING_ASSETS}/crater-lake.webp`,
    altText: "A volcanic lake radiating heat",
  },
  {
    id: 12,
    name: "Moonlit Reflection Pool",
    fishingXP: 70,
    fishingXPUnlock: totalXpForLevel(88),
    fishingDelay: 8000,
    fishingLootIds: [314, 319],
    picture: `${FISHING_ASSETS}/moon-pool.webp`,
    altText: "Still waters reflecting the full moon",
    rareDropChancePercent: 1,
    rareDropItemIds: [RING_IDS.moonlitReflection],
  },
  {
    id: 13,
    name: "Falling Star Stream",
    fishingXP: 75,
    fishingXPUnlock: totalXpForLevel(92),
    fishingDelay: 8200,
    fishingLootIds: [315, 320],
    picture: `${FISHING_ASSETS}/star-stream.webp`,
    altText: "A stream where stars are said to fall",
  },
  {
    id: 14,
    name: "Void Rift Waters",
    fishingXP: 82,
    fishingXPUnlock: totalXpForLevel(96),
    fishingDelay: 8500,
    fishingLootIds: [318, 321],
    picture: `${FISHING_ASSETS}/void-rift.webp`,
    altText: "Waters bordering a spatial rift",
  },
  {
    id: 15,
    name: "Primordial Spirit Sea",
    fishingXP: 95,
    fishingXPUnlock: totalXpForLevel(99),
    fishingDelay: 9000,
    fishingLootIds: [322, 312, 320],
    picture: `${FISHING_ASSETS}/primordial-sea.webp`,
    altText: "Ancient sea filled with primordial Qi",
    rareDropChancePercent: 1,
    rareDropItemIds: [AMULET_IDS.transcendentDao],
  },
];

export const fishTypes: Item[] = [
  {
    id: 301,
    name: "Spirit Minnow",
    description: "A small fish touched by Qi. Can be used in pills. Restores 1 Qi.",
    price: 1,
    quantity: 1,
    picture: `${FISH_ASSETS}/spirit-minnow.webp`,
    value: 1,
    effect: "qi",
  },
  {
    id: 302,
    name: "River Carp",
    description: "Common in Spirit River. Good for cooking.",
    price: 3,
    quantity: 1,
    picture: `${FISH_ASSETS}/river-carp.webp`,
    value: 2,
    effect: "vitality",
  },
  {
    id: 303,
    name: "Jade Tuna",
    description: "Large spirit fish from the Spirit Sea.",
    price: 5,
    quantity: 1,
    picture: `${FISH_ASSETS}/jade-tuna.webp`,
    value: 3,
    effect: "vitality",
  },
  {
    id: 304,
    name: "Silver Mackerel",
    description: "Swift fish rich in spiritual energy.",
    price: 2,
    quantity: 1,
    picture: `${FISH_ASSETS}/silver-mackerel.webp`,
    value: 2,
    effect: "vitality",
  },
  {
    id: 305,
    name: "Abyssal Puffer",
    description: "Rare fish from the deep. Handle with care when preparing.",
    price: 7,
    quantity: 1,
    picture: `${FISH_ASSETS}/abyssal-puffer.webp`,
    value: 5,
    effect: "vitality",
  },
  {
    id: 306,
    name: "Lotus Koi",
    description: "A koi raised among spirit lotuses. Calms the mind.",
    price: 6,
    quantity: 1,
    picture: `${FISH_ASSETS}/lotus-koi.webp`,
    value: 4,
    effect: "qi",
  },
  {
    id: 307,
    name: "Azure Scale Eel",
    description: "An eel crackling with faint lightning Qi.",
    price: 8,
    quantity: 1,
    picture: `${FISH_ASSETS}/azure-eel.webp`,
    value: 5,
    effect: "qi",
  },
  {
    id: 308,
    name: "Golden Spine Bass",
    description: "A rare bass with golden bones prized by alchemists.",
    price: 10,
    quantity: 1,
    picture: `${FISH_ASSETS}/golden-bass.webp`,
    value: 6,
    effect: "vitality",
  },
  {
    id: 309,
    name: "Frostfin Trout",
    description: "Lives in icy waters. Body cold as jade.",
    price: 12,
    quantity: 1,
    picture: `${FISH_ASSETS}/frostfin-trout.webp`,
    value: 7,
    effect: "vitality",
  },
  {
    id: 310,
    name: "Shadow Catfish",
    description: "Feeds in darkness. Favored by demonic cultivators.",
    price: 14,
    quantity: 1,
    picture: `${FISH_ASSETS}/shadow-catfish.webp`,
    value: 8,
    effect: "qi",
  },
  {
    id: 311,
    name: "Celestial Salmon",
    description: "Swims against spiritual currents of heaven.",
    price: 18,
    quantity: 1,
    picture: `${FISH_ASSETS}/celestial-salmon.webp`,
    value: 10,
    effect: "vitality",
  },
  {
    id: 312,
    name: "Dragon Vein Sturgeon",
    description: "Said to drink from dragon veins beneath the world.",
    price: 25,
    quantity: 1,
    picture: `${FISH_ASSETS}/dragon-sturgeon.webp`,
    value: 14,
    effect: "qi",
  },
  {
    id: 313,
    name: "Emberfin Snapper",
    description: "A fish with warm, glowing scales. Said to live near magma springs.",
    price: 16,
    quantity: 1,
    picture: `${FISH_ASSETS}/emberfin-snapper.webp`,
    value: 9,
    effect: "vitality",
  },
  {
    id: 314,
    name: "Moonwhisker Carp",
    description: "Active only under moonlight. Enhances spiritual awareness.",
    price: 18,
    quantity: 1,
    picture: `${FISH_ASSETS}/moonwhisker-carp.webp`,
    value: 10,
    effect: "qi",
  },
  {
    id: 315,
    name: "Starfall Guppy",
    description: "Tiny fish that shimmer like falling stars.",
    price: 14,
    quantity: 1,
    picture: `${FISH_ASSETS}/starfall-guppy.webp`,
    value: 8,
    effect: "qi",
  },
  {
    id: 316,
    name: "Thunderjaw Pike",
    description: "Its bite releases a crack of thunder.",
    price: 22,
    quantity: 1,
    picture: `${FISH_ASSETS}/thunderjaw-pike.webp`,
    value: 12,
    effect: "vitality",
  },
  {
    id: 317,
    name: "Verdant Scale Tilapia",
    description: "Feeds on spirit herbs. Favored in alchemy.",
    price: 17,
    quantity: 1,
    picture: `${FISH_ASSETS}/verdant-tilapia.webp`,
    value: 9,
    effect: "qi",
  },
  {
    id: 318,
    name: "Void Lantern Fish",
    description: "A deep-water fish that glows like a ghostly lantern.",
    price: 24,
    quantity: 1,
    picture: `${FISH_ASSETS}/void-lantern.webp`,
    value: 13,
    effect: "qi",
  },
  {
    id: 319,
    name: "Crimson Banner Koi",
    description: "Symbol of fortune among sect elders.",
    price: 26,
    quantity: 1,
    picture: `${FISH_ASSETS}/crimson-koi.webp`,
    value: 14,
    effect: "vitality",
  },
  {
    id: 320,
    name: "Heaven's Mirror Ray",
    description: "Its body reflects the sky like a mirror.",
    price: 28,
    quantity: 1,
    picture: `${FISH_ASSETS}/mirror-ray.webp`,
    value: 15,
    effect: "qi",
  },
  {
    id: 321,
    name: "Nine-Whisker Catfish",
    description: "An ancient breed rumored to live for centuries.",
    price: 30,
    quantity: 1,
    picture: `${FISH_ASSETS}/ninewhisker-catfish.webp`,
    value: 16,
    effect: "vitality",
  },
  {
    id: 322,
    name: "Mythic Pearl Eel",
    description: "Occasionally forms spirit pearls within its body.",
    price: 35,
    quantity: 1,
    picture: `${FISH_ASSETS}/pearl-eel.webp`,
    value: 18,
    effect: "qi",
  },
];

/** Mining areas: unlock by level (stored as XP via totalXpForMiningLevel). */
export const miningAreaData: MiningAreaI[] = [
  {
    id: 1,
    name: "Copper Ore",
    miningXP: 1,
    miningXPUnlock: totalXpForMiningLevel(1),
    miningDelay: 4000,
    miningLootId: 501,
    picture: `${MINING_ASSETS}/copper-mine.webp`,
    altText: "Copper ore vein",
  },
  {
    id: 2,
    name: "Iron Ore",
    miningXP: 2,
    miningXPUnlock: totalXpForMiningLevel(5),
    miningDelay: 5000,
    miningLootId: 502,
    picture: `${MINING_ASSETS}/iron-mine.webp`,
    altText: "Iron ore vein",
  },
  {
    id: 3,
    name: "Spirit Vein",
    miningXP: 4,
    miningXPUnlock: totalXpForMiningLevel(10),
    miningDelay: 6000,
    miningLootId: 503,
    picture: `${MINING_ASSETS}/spirit-vein.webp`,
    altText: "Spirit stone vein",
  },
  {
    id: 4,
    name: "Tin Seam",
    miningXP: 5,
    miningXPUnlock: totalXpForMiningLevel(15),
    miningDelay: 6200,
    miningLootId: 504,
    picture: `${MINING_ASSETS}/tin-seam.webp`,
    altText: "Tin ore seam",
  },
  {
    id: 5,
    name: "Jade Deposit",
    miningXP: 7,
    miningXPUnlock: totalXpForMiningLevel(20),
    miningDelay: 6500,
    miningLootId: 505,
    picture: `${MINING_ASSETS}/jade-deposit.webp`,
    altText: "Jade ore deposit",
  },
  {
    id: 6,
    name: "Silver Lode",
    miningXP: 9,
    miningXPUnlock: totalXpForMiningLevel(30),
    miningDelay: 7000,
    miningLootId: 506,
    picture: `${MINING_ASSETS}/silver-lode.webp`,
    altText: "Silver ore lode",
  },
  {
    id: 7,
    name: "Gold Vein",
    miningXP: 12,
    miningXPUnlock: totalXpForMiningLevel(40),
    miningDelay: 7600,
    miningLootId: 507,
    picture: `${MINING_ASSETS}/gold-vein.webp`,
    altText: "Gold ore vein",
  },
  {
    id: 8,
    name: "Obsidian Ridge",
    miningXP: 16,
    miningXPUnlock: totalXpForMiningLevel(50),
    miningDelay: 8200,
    miningLootId: 509,
    picture: `${MINING_ASSETS}/obsidian-ridge.webp`,
    altText: "Obsidian outcrop",
  },
  {
    id: 9,
    name: "Thunder Crystal Cavern",
    miningXP: 18,
    miningXPUnlock: totalXpForMiningLevel(50),
    miningDelay: 8500,
    miningLootId: 508,
    picture: `${MINING_ASSETS}/thunder-cavern.webp`,
    altText: "Cavern with lightning-charged crystals",
  },
  {
    id: 10,
    name: "Fallen Star Crater",
    miningXP: 24,
    miningXPUnlock: totalXpForMiningLevel(60),
    miningDelay: 9000,
    miningLootId: 510,
    picture: `${MINING_ASSETS}/star-crater.webp`,
    altText: "Meteor crater rich with star iron",
  },
  {
    id: 11,
    name: "Voidstone Quarry",
    miningXP: 32,
    miningXPUnlock: totalXpForMiningLevel(70),
    miningDelay: 9800,
    miningLootId: 511,
    picture: `${MINING_ASSETS}/voidstone-quarry.webp`,
    altText: "Quarry of light-bending voidstone",
  },
  {
    id: 12,
    name: "Dragonbone Strata",
    miningXP: 42,
    miningXPUnlock: totalXpForMiningLevel(80),
    miningDelay: 10500,
    miningLootId: 512,
    picture: `${MINING_ASSETS}/dragonbone-strata.webp`,
    altText: "Ancient strata resembling dragon bones",
  },
  {
    id: 13,
    name: "Celestial Crystal Spire",
    miningXP: 58,
    miningXPUnlock: totalXpForMiningLevel(90),
    miningDelay: 11500,
    miningLootId: 513,
    picture: `${MINING_ASSETS}/celestial-spire.webp`,
    altText: "Spire of radiant celestial crystals",
  },
  {
    id: 14,
    name: "Primordial Spirit Geode",
    miningXP: 70,
    miningXPUnlock: totalXpForMiningLevel(95),
    miningDelay: 12500,
    miningLootId: 513,
    picture: `${MINING_ASSETS}/primordial-geode.webp`,
    altText: "A geode overflowing with condensed heavenly Qi",
  },
];

export const oreTypes: Item[] = [
  {
    id: 501,
    name: "Copper Ore",
    description: "Common copper ore. Used for basic tools and fittings.",
    price: 1,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/copper-ore.webp`,
    value: 1,
    effect: "none",
  },
  {
    id: 502,
    name: "Iron Ore",
    description: "Reliable iron ore for weapons and armor.",
    price: 2,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/iron-ore.webp`,
    value: 2,
    effect: "none",
  },
  {
    id: 503,
    name: "Spirit Stone",
    description: "A crystalline stone infused with Qi. Used in formations and cultivation.",
    price: 5,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/spirit-stone.webp`,
    value: 4,
    effect: "qi",
  },
  {
    id: 504,
    name: "Tin Ore",
    description: "Soft metal ore used to alloy bronze and reinforce gear.",
    price: 2,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/tin-ore.webp`,
    value: 2,
    effect: "none",
  },
  {
    id: 505,
    name: "Jade Ore",
    description: "Dense jade-like mineral prized for talismans and seals.",
    price: 6,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/jade-ore.webp`,
    value: 5,
    effect: "qi",
  },
  {
    id: 506,
    name: "Silver Ore",
    description: "Conductive metal used in spirit circuits and charms.",
    price: 8,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/silver-ore.webp`,
    value: 6,
    effect: "none",
  },
  {
    id: 507,
    name: "Gold Ore",
    description: "Rare noble metal used for high-grade crafting and tribute.",
    price: 10,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/gold-ore.webp`,
    value: 7,
    effect: "none",
  },
  {
    id: 508,
    name: "Thunder Crystal",
    description: "A crackling crystal that stores lightning Qi.",
    price: 14,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/thunder-crystal.webp`,
    value: 10,
    effect: "qi",
  },
  {
    id: 509,
    name: "Obsidian Shard",
    description: "Volcanic glass used for sharp blades and dark arrays.",
    price: 12,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/obsidian.webp`,
    value: 9,
    effect: "none",
  },
  {
    id: 510,
    name: "Star Iron",
    description: "Meteor-forged iron that holds enchantments unusually well.",
    price: 18,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/star-iron.webp`,
    value: 12,
    effect: "vitality",
  },
  {
    id: 511,
    name: "Voidstone",
    description: "A heavy stone that bends light. Used in spatial storage and rifts.",
    price: 22,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/voidstone.webp`,
    value: 14,
    effect: "qi",
  },
  {
    id: 512,
    name: "Dragonbone Ore",
    description: "A bone-white mineral said to form near dragon veins.",
    price: 28,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/dragonbone-ore.webp`,
    value: 18,
    effect: "vitality",
  },
  {
    id: 513,
    name: "Celestial Essence Crystal",
    description: "Radiant crystal condensed from heavenly Qi. Extremely valuable.",
    price: 40,
    quantity: 1,
    picture: `${MINING_LOOT_ASSETS}/celestial-crystal.webp`,
    value: 25,
    effect: "qi",
  },
];

/** Gathering areas: unlock by level (stored as XP via totalXpForGatheringLevel). Spread varied for 1–99. */
export const gatheringAreaData: GatheringAreaI[] = [
  {
    id: 1,
    name: "Mortal Oak Grove",
    gatheringXP: 1,
    gatheringXPUnlock: totalXpForGatheringLevel(1),
    gatheringDelay: 4000,
    gatheringLootIds: [601],
    picture: `${GATHERING_ASSETS}/mortal-oak-grove.webp`,
    altText: "Mortal Oak Grove",
  },
  {
    id: 2,
    name: "Hundred Herb Garden",
    gatheringXP: 1,
    gatheringXPUnlock: totalXpForGatheringLevel(1),
    gatheringDelay: 4000,
    gatheringLootIds: [611, 612],
    picture: `${GATHERING_ASSETS}/hundred-herb-garden.webp`,
    altText: "Hundred Herb Garden",
  },
  {
    id: 3,
    name: "Iron Bamboo Forest",
    gatheringXP: 2,
    gatheringXPUnlock: totalXpForGatheringLevel(8),
    gatheringDelay: 4500,
    gatheringLootIds: [602],
    picture: `${GATHERING_ASSETS}/iron-bamboo-forest.webp`,
    altText: "Iron Bamboo Forest",
  },
  {
    id: 4,
    name: "Spirit Grass Valley",
    gatheringXP: 4,
    gatheringXPUnlock: totalXpForGatheringLevel(16),
    gatheringDelay: 5000,
    gatheringLootIds: [613, 614],
    picture: `${GATHERING_ASSETS}/spirit-grass-valley.webp`,
    altText: "Spirit Grass Valley",
  },
  {
    id: 5,
    name: "Ancient Cypress Peak",
    gatheringXP: 6,
    gatheringXPUnlock: totalXpForGatheringLevel(24),
    gatheringDelay: 5500,
    gatheringLootIds: [603],
    picture: `${GATHERING_ASSETS}/ancient-cypress-peak.webp`,
    altText: "Ancient Cypress Peak",
  },
  {
    id: 6,
    name: "Heavenly Herb Cliff",
    gatheringXP: 8,
    gatheringXPUnlock: totalXpForGatheringLevel(32),
    gatheringDelay: 6000,
    gatheringLootIds: [614, 615, 616],
    picture: `${GATHERING_ASSETS}/heavenly-herb-cliff.webp`,
    altText: "Heavenly Herb Cliff",
  },
  {
    id: 7,
    name: "Pine Hollow",
    gatheringXP: 10,
    gatheringXPUnlock: totalXpForGatheringLevel(41),
    gatheringDelay: 6500,
    gatheringLootIds: [604],
    picture: `${GATHERING_ASSETS}/pine-hollow.webp`,
    altText: "Dense pine grove",
  },
  {
    id: 8,
    name: "Moonlit Herb Patch",
    gatheringXP: 12,
    gatheringXPUnlock: totalXpForGatheringLevel(50),
    gatheringDelay: 7000,
    gatheringLootIds: [616, 617],
    picture: `${GATHERING_ASSETS}/moonlit-herb-patch.webp`,
    altText: "Herbs that bloom under moonlight",
  },
  {
    id: 9,
    name: "Ebony Grove",
    gatheringXP: 14,
    gatheringXPUnlock: totalXpForGatheringLevel(59),
    gatheringDelay: 7500,
    gatheringLootIds: [605],
    picture: `${GATHERING_ASSETS}/ebony-grove.webp`,
    altText: "Dark ebony trees",
  },
  {
    id: 10,
    name: "Star Moss Vale",
    gatheringXP: 16,
    gatheringXPUnlock: totalXpForGatheringLevel(68),
    gatheringDelay: 8000,
    gatheringLootIds: [617, 618],
    picture: `${GATHERING_ASSETS}/star-moss-vale.webp`,
    altText: "Valley of star-catching moss",
  },
  {
    id: 11,
    name: "Void Willow Stand",
    gatheringXP: 20,
    gatheringXPUnlock: totalXpForGatheringLevel(76),
    gatheringDelay: 8500,
    gatheringLootIds: [606],
    picture: `${GATHERING_ASSETS}/void-willow-stand.webp`,
    altText: "Willows that drink from the void",
  },
  {
    id: 12,
    name: "Dragon Ash Thicket",
    gatheringXP: 24,
    gatheringXPUnlock: totalXpForGatheringLevel(83),
    gatheringDelay: 9000,
    gatheringLootIds: [607],
    picture: `${GATHERING_ASSETS}/dragon-ash-thicket.webp`,
    altText: "Ashen wood from dragon lands",
  },
  {
    id: 13,
    name: "Primordial Herb Garden",
    gatheringXP: 28,
    gatheringXPUnlock: totalXpForGatheringLevel(88),
    gatheringDelay: 9500,
    gatheringLootIds: [618, 619, 620],
    picture: `${GATHERING_ASSETS}/primordial-herb-garden.webp`,
    altText: "Ancient herbs from the dawn of Qi",
    rareDropChancePercent: 1,
    rareDropItemIds: [AMULET_IDS.spiritHerbCharm],
  },
  {
    id: 14,
    name: "Celestial Bamboo Grove",
    gatheringXP: 34,
    gatheringXPUnlock: totalXpForGatheringLevel(92),
    gatheringDelay: 10000,
    gatheringLootIds: [608],
    picture: `${GATHERING_ASSETS}/celestial-bamboo-grove.webp`,
    altText: "Bamboo touched by heavenly Qi",
  },
  {
    id: 15,
    name: "Transcendent Spirit Peak",
    gatheringXP: 42,
    gatheringXPUnlock: totalXpForGatheringLevel(99),
    gatheringDelay: 11000,
    gatheringLootIds: [620, 621, 622],
    picture: `${GATHERING_ASSETS}/transcendent-spirit-peak.webp`,
    altText: "Peak where spirit herbs reach beyond",
    rareDropChancePercent: 1,
    rareDropItemIds: [RING_IDS.primordialSeal],
  },
];

export const woodTypes: Item[] = [
  {
    id: 601,
    name: "Oak Wood",
    description: "Common oak. Used for weapons and to light the alchemy forge.",
    price: 2,
    quantity: 1,
    picture: `${GATHERING_ITEMS}/item-oak-wood.webp`,
    value: 0,
  },
  {
    id: 602,
    name: "Iron Bamboo",
    description: "Hard bamboo favoured by cultivators. Used in forging and cooking fires.",
    price: 5,
    quantity: 1,
    picture: `${GATHERING_ITEMS}/item-iron-bamboo.webp`,
    value: 0,
  },
  {
    id: 603,
    name: "Spirit Cypress Wood",
    description: "Wood touched by Qi. Used for spirit weapons and high-grade alchemy.",
    price: 12,
    quantity: 1,
    picture: `${GATHERING_ITEMS}/item-spirit-cypress.webp`,
    value: 0,
  },
  {
    id: 604,
    name: "Pine Wood",
    description: "Resinous pine. Burns long; used in alchemy and campfires.",
    price: 4,
    quantity: 1,
    picture: `${GATHERING_ITEMS}/item-pine-wood.webp`,
    value: 0,
  },
  {
    id: 605,
    name: "Ebony Wood",
    description: "Dense dark wood. Used for high-grade crafting and arrays.",
    price: 14,
    quantity: 1,
    picture: `${GATHERING_ITEMS}/item-ebony-wood.webp`,
    value: 0,
  },
  {
    id: 606,
    name: "Void Willow",
    description: "Willow that grows near rifts. Used in spatial and void arrays.",
    price: 20,
    quantity: 1,
    picture: `${GATHERING_ITEMS}/item-void-willow.webp`,
    value: 0,
  },
  {
    id: 607,
    name: "Dragon Ash Wood",
    description: "Ashen wood from dragon territories. Used in top-tier forging.",
    price: 26,
    quantity: 1,
    picture: `${GATHERING_ITEMS}/item-dragon-ash-wood.webp`,
    value: 0,
  },
  {
    id: 608,
    name: "Celestial Bamboo",
    description: "Bamboo infused with heavenly Qi. Used in transcendent alchemy.",
    price: 35,
    quantity: 1,
    picture: `${GATHERING_ITEMS}/item-celestial-bamboo.webp`,
    value: 0,
  },
];

export const herbTypes: Item[] = [
  {
    id: 611,
    name: "Common Herb",
    description: "A basic herb. Used in pills and alchemy.",
    price: 1,
    quantity: 1,
    picture: `${GATHERING_ITEMS}/item-common-herb.webp`,
    value: 0,
  },
  {
    id: 612,
    name: "Spirit Leaf",
    description: "Leaf imbued with faint Qi. Used in low-grade pills.",
    price: 2,
    quantity: 1,
    picture: `${GATHERING_ITEMS}/item-spirit-leaf.webp`,
    value: 0,
  },
  {
    id: 613,
    name: "Spirit Grass",
    description: "Grass from spirit-rich soil. Used in alchemy pills.",
    price: 4,
    quantity: 1,
    picture: `${GATHERING_ITEMS}/item-spirit-grass.webp`,
    value: 0,
  },
  {
    id: 614,
    name: "Silver Leaf",
    description: "Rare herb with a silvery sheen. Used in refinement pills.",
    price: 6,
    quantity: 1,
    picture: `${GATHERING_ITEMS}/item-silver-leaf.webp`,
    value: 0,
  },
  {
    id: 615,
    name: "Jade Spirit Herb",
    description: "Precious herb favoured in high-level alchemy.",
    price: 10,
    quantity: 1,
    picture: `${GATHERING_ITEMS}/item-jade-spirit-herb.webp`,
    value: 0,
  },
  {
    id: 616,
    name: "Heavenly Ginseng",
    description: "Rare ginseng said to touch the heavens. Used in breakthrough pills.",
    price: 15,
    quantity: 1,
    picture: `${GATHERING_ITEMS}/item-heavenly-ginseng.webp`,
    value: 0,
  },
  {
    id: 617,
    name: "Moon Petal",
    description: "Herb that blooms under the full moon. Used in awareness pills.",
    price: 12,
    quantity: 1,
    picture: `${GATHERING_ITEMS}/item-moon-petal.webp`,
    value: 0,
  },
  {
    id: 618,
    name: "Star Moss",
    description: "Moss that glows like starlight. Used in stellar alchemy.",
    price: 18,
    quantity: 1,
    picture: `${GATHERING_ITEMS}/item-star-moss.webp`,
    value: 0,
  },
  {
    id: 619,
    name: "Primordial Root",
    description: "Root from the dawn of Qi. Used in ancient formulae.",
    price: 22,
    quantity: 1,
    picture: `${GATHERING_ITEMS}/item-primordial-root.webp`,
    value: 0,
  },
  {
    id: 620,
    name: "Void Bloom",
    description: "Flower that grows near rifts. Used in void-attuned pills.",
    price: 28,
    quantity: 1,
    picture: `${GATHERING_ITEMS}/item-void-bloom.webp`,
    value: 0,
  },
  {
    id: 621,
    name: "Celestial Lotus",
    description: "Lotus touched by heaven. Used in transcendent pills.",
    price: 34,
    quantity: 1,
    picture: `${GATHERING_ITEMS}/item-celestial-lotus.webp`,
    value: 0,
  },
  {
    id: 622,
    name: "Transcendent Spirit Herb",
    description: "Herb that transcends mortal classification. Peak alchemy ingredient.",
    price: 45,
    quantity: 1,
    picture: `${GATHERING_ITEMS}/item-transcendent-herb.webp`,
    value: 0,
  },
];

/** All gathering loot (wood + herbs) for lookup when completing a gather. */
export const gatheringLootTypes: Item[] = [...woodTypes, ...herbTypes];
